import type { Unit } from '@/lib/domain/models'

import { createGeneratedLesson } from '@/content/units/unit-helpers'

const unitId = 'unit-04'
const personalDetailsId = 'unit-04-personal-details'
const familyCircleId = 'unit-04-family-circle'
const timeWordsId = 'unit-04-time-words'

export const unit04: Unit = {
	id: unitId,
	order: 4,
	title: 'Life and People',
	description: 'Biographical details, family, jobs, and everyday time words.',
	theme: 'Coral city',
	bannerTitle: 'Share your life',
	bannerSubtitle: 'Say where you live, what you do, and who matters to you.',
	categories: [
		{
			id: personalDetailsId,
			unitId,
			order: 1,
			title: 'Personal Details',
			subtitle: 'Give basic information',
			description: 'Ask and answer simple biographical questions.',
			themeColor: 'from-rose-400 to-orange-500',
			accentColor: 'bg-rose-400',
			icon: 'chat',
			hasGuidebook: true,
			lessons: [
				createGeneratedLesson({
					id: 'lesson-biographical-info',
					unitId,
					categoryId: personalDetailsId,
					order: 1,
					title: 'About Me',
					subtitle: 'Share simple details',
					description: 'Talk about your age, name, and basic personal details.',
					grammarNote:
						'Use "Ilang taon ka na?" for age and short replies like "Dalawampu ako." in friendly speech.',
					color: 'from-rose-400 to-pink-500',
					introCards: [
						{
							id: 'intro-bio-1',
							kind: 'phrase',
							tagalog: 'Ilang taon ka na?',
							meaning: 'How old are you?',
							audioText: 'Ilang taon ka na?',
							example: 'A common question when getting to know someone.',
							emoji: 'Age',
						},
						{
							id: 'intro-bio-2',
							kind: 'phrase',
							tagalog: 'Dalawampu ako',
							meaning: 'I am twenty',
							audioText: 'Dalawampu ako',
							example: 'A compact age answer.',
							emoji: 'Twenty',
						},
						{
							id: 'intro-bio-3',
							kind: 'word',
							tagalog: 'Taga',
							meaning: 'From',
							audioText: 'Taga',
							example: 'Use it in "Taga Maynila ako."',
							emoji: 'From',
						},
					],
					matchPairs: [
						{ left: 'How old are you?', right: 'Ilang taon ka na?' },
						{ left: 'I am twenty', right: 'Dalawampu ako' },
						{ left: 'from', right: 'Taga' },
					],
					buildPrompt: 'Build "I am twenty."',
					buildOptions: ['Dalawampu', 'ako', 'ka', 'taga'],
					correctSequence: ['Dalawampu', 'ako'],
					blankPrompt: 'Complete the question.',
					sentenceTemplate: 'Ilang ___ ka na?',
					acceptableAnswers: ['taon', 'Taon'],
					placeholder: 'Missing word',
					listeningPrompt: 'What question do you hear?',
					audioText: 'Ilang taon ka na?',
					listeningOptions: [
						'How old are you?',
						'Where are you from?',
						'What is your job?',
					],
					correctAnswer: 'How old are you?',
					speakingPrompt: 'Say "I am twenty."',
					expectedTranscript: 'Dalawampu ako.',
					referenceTranslation: 'I am twenty.',
				}),
				createGeneratedLesson({
					id: 'lesson-where-you-live',
					unitId,
					categoryId: personalDetailsId,
					order: 2,
					title: 'Where You Live',
					subtitle: 'Talk about home',
					description: 'Say where you live and ask others where they are from.',
					grammarNote:
						'Use "Nakatira ako sa..." for where you live. "Saan ka nakatira?" asks where someone lives.',
					color: 'from-orange-400 to-amber-500',
					introCards: [
						{
							id: 'intro-live-1',
							kind: 'phrase',
							tagalog: 'Saan ka nakatira?',
							meaning: 'Where do you live?',
							audioText: 'Saan ka nakatira?',
							example: 'A useful personal information question.',
							emoji: 'Where',
						},
						{
							id: 'intro-live-2',
							kind: 'phrase',
							tagalog: 'Nakatira ako sa Cebu',
							meaning: 'I live in Cebu',
							audioText: 'Nakatira ako sa Cebu',
							example: 'Swap in any city or place name.',
							emoji: 'City',
						},
						{
							id: 'intro-live-3',
							kind: 'word',
							tagalog: 'Lungsod',
							meaning: 'City',
							audioText: 'Lungsod',
							example: 'Useful for places and addresses.',
							emoji: 'City',
						},
					],
					matchPairs: [
						{ left: 'Where do you live?', right: 'Saan ka nakatira?' },
						{ left: 'I live in Cebu', right: 'Nakatira ako sa Cebu' },
						{ left: 'city', right: 'Lungsod' },
					],
					buildPrompt: 'Build "I live in Cebu."',
					buildOptions: ['Nakatira', 'ako', 'sa', 'Cebu', 'Maynila'],
					correctSequence: ['Nakatira', 'ako', 'sa', 'Cebu'],
					blankPrompt: 'Complete the place sentence.',
					sentenceTemplate: 'Nakatira ako sa ___.',
					acceptableAnswers: ['Cebu', 'cebu'],
					placeholder: 'Place',
					listeningPrompt: 'What does the speaker say?',
					audioText: 'Saan ka nakatira?',
					listeningOptions: [
						'Where do you live?',
						'What is your name?',
						'Who is your friend?',
					],
					correctAnswer: 'Where do you live?',
					speakingPrompt: 'Say "Where do you live?"',
					expectedTranscript: 'Saan ka nakatira?',
					referenceTranslation: 'Where do you live?',
					finalExercise: 'listen-repeat',
				}),
			],
		},
		{
			id: familyCircleId,
			unitId,
			order: 2,
			title: 'Family Circle',
			subtitle: 'Introduce people',
			description: 'Talk about family members and introduce others.',
			themeColor: 'from-fuchsia-400 to-rose-500',
			accentColor: 'bg-fuchsia-400',
			icon: 'star',
			lessons: [
				createGeneratedLesson({
					id: 'lesson-family-members',
					unitId,
					categoryId: familyCircleId,
					order: 1,
					title: 'Family Members',
					subtitle: 'Name close family',
					description: 'Use everyday family words in short sentences.',
					grammarNote:
						'Possession often comes after the noun: "nanay ko" means "my mother" and "kapatid ko" means "my sibling."',
					color: 'from-fuchsia-400 to-pink-500',
					introCards: [
						{
							id: 'intro-family-1',
							kind: 'word',
							tagalog: 'Nanay',
							meaning: 'Mother',
							audioText: 'Nanay',
							example: '"Nanay ko" means "my mother."',
							emoji: 'Mother',
						},
						{
							id: 'intro-family-2',
							kind: 'word',
							tagalog: 'Tatay',
							meaning: 'Father',
							audioText: 'Tatay',
							example: '"Tatay ko" means "my father."',
							emoji: 'Father',
						},
						{
							id: 'intro-family-3',
							kind: 'word',
							tagalog: 'Kapatid',
							meaning: 'Sibling',
							audioText: 'Kapatid',
							example:
								'Use it for brother or sister unless you need to be specific.',
							emoji: 'Sibling',
						},
					],
					matchPairs: [
						{ left: 'mother', right: 'Nanay' },
						{ left: 'father', right: 'Tatay' },
						{ left: 'sibling', right: 'Kapatid' },
					],
					buildPrompt: 'Build "my mother."',
					buildOptions: ['Nanay', 'ko', 'mo', 'Tatay'],
					correctSequence: ['Nanay', 'ko'],
					blankPrompt: 'Complete the phrase.',
					sentenceTemplate: 'Kapatid ___',
					acceptableAnswers: ['ko', 'Ko'],
					placeholder: 'my',
					listeningPrompt: 'Which family word do you hear?',
					audioText: 'Tatay',
					listeningOptions: ['father', 'mother', 'sibling'],
					correctAnswer: 'father',
					speakingPrompt: 'Say "my sibling."',
					expectedTranscript: 'Kapatid ko.',
					referenceTranslation: 'My sibling.',
				}),
				createGeneratedLesson({
					id: 'lesson-introduce-others',
					unitId,
					categoryId: familyCircleId,
					order: 2,
					title: 'Introduce Others',
					subtitle: 'Say who someone is',
					description:
						'Introduce another person with simple respectful phrasing.',
					grammarNote:
						'Use "Ito si..." for "This is..." when introducing a named person.',
					color: 'from-pink-400 to-rose-500',
					introCards: [
						{
							id: 'intro-others-1',
							kind: 'phrase',
							tagalog: 'Ito si Ana',
							meaning: 'This is Ana',
							audioText: 'Ito si Ana',
							example: 'Use it when introducing someone by name.',
							emoji: 'Introduce',
						},
						{
							id: 'intro-others-2',
							kind: 'phrase',
							tagalog: 'Kaibigan ko siya',
							meaning: 'He or she is my friend',
							audioText: 'Kaibigan ko siya',
							example: 'A friendly follow-up introduction.',
							emoji: 'Friend',
						},
						{
							id: 'intro-others-3',
							kind: 'word',
							tagalog: 'Siya',
							meaning: 'He / she',
							audioText: 'Siya',
							example: 'Tagalog uses one common pronoun for he and she.',
							emoji: 'Person',
						},
					],
					matchPairs: [
						{ left: 'This is Ana', right: 'Ito si Ana' },
						{ left: 'my friend', right: 'Kaibigan ko' },
						{ left: 'he or she', right: 'Siya' },
					],
					buildPrompt: 'Build "This is Ana."',
					buildOptions: ['Ito', 'si', 'Ana', 'ako'],
					correctSequence: ['Ito', 'si', 'Ana'],
					blankPrompt: 'Complete the introduction.',
					sentenceTemplate: 'Kaibigan ko ___.',
					acceptableAnswers: ['siya', 'Siya'],
					placeholder: 'he/she',
					listeningPrompt: 'What introduction do you hear?',
					audioText: 'Ito si Ana',
					listeningOptions: ['This is Ana', 'I am Ana', 'Where is Ana?'],
					correctAnswer: 'This is Ana',
					speakingPrompt: 'Say "This is Ana."',
					expectedTranscript: 'Ito si Ana.',
					referenceTranslation: 'This is Ana.',
					finalExercise: 'listen-repeat',
				}),
			],
		},
		{
			id: timeWordsId,
			unitId,
			order: 3,
			title: 'Time Words',
			subtitle: 'Use days and months',
			description: 'Build simple schedule phrases with days, months, and time.',
			themeColor: 'from-amber-400 to-yellow-500',
			accentColor: 'bg-amber-400',
			icon: 'spark',
			hasRewardChest: true,
			lessons: [
				createGeneratedLesson({
					id: 'lesson-days-months',
					unitId,
					categoryId: timeWordsId,
					order: 1,
					title: 'Days and Months',
					subtitle: 'Name calendar words',
					description: 'Recognize common days and months in simple plans.',
					grammarNote:
						'Many day and month names are borrowed from Spanish, so words like "Lunes" and "Enero" may feel familiar.',
					color: 'from-amber-400 to-orange-500',
					introCards: [
						{
							id: 'intro-calendar-1',
							kind: 'word',
							tagalog: 'Lunes',
							meaning: 'Monday',
							audioText: 'Lunes',
							example: 'Use it for weekly plans.',
							emoji: 'Monday',
						},
						{
							id: 'intro-calendar-2',
							kind: 'word',
							tagalog: 'Biyernes',
							meaning: 'Friday',
							audioText: 'Biyernes',
							example: 'A useful word for weekend plans.',
							emoji: 'Friday',
						},
						{
							id: 'intro-calendar-3',
							kind: 'word',
							tagalog: 'Enero',
							meaning: 'January',
							audioText: 'Enero',
							example: 'A common month name.',
							emoji: 'January',
						},
					],
					matchPairs: [
						{ left: 'Monday', right: 'Lunes' },
						{ left: 'Friday', right: 'Biyernes' },
						{ left: 'January', right: 'Enero' },
					],
					buildPrompt: 'Build "on Monday."',
					buildOptions: ['Sa', 'Lunes', 'Enero', 'ako'],
					correctSequence: ['Sa', 'Lunes'],
					blankPrompt: 'Complete the schedule phrase.',
					sentenceTemplate: 'Sa ___ ako pupunta.',
					acceptableAnswers: ['Biyernes', 'biyernes'],
					placeholder: 'Day',
					listeningPrompt: 'Which day do you hear?',
					audioText: 'Biyernes',
					listeningOptions: ['Friday', 'Monday', 'January'],
					correctAnswer: 'Friday',
					speakingPrompt: 'Say "on Monday."',
					expectedTranscript: 'Sa Lunes.',
					referenceTranslation: 'On Monday.',
				}),
				createGeneratedLesson({
					id: 'lesson-simple-schedule',
					unitId,
					categoryId: timeWordsId,
					order: 2,
					title: 'Simple Schedule',
					subtitle: 'Talk about when',
					description: 'Use today, tomorrow, and later in everyday plans.',
					grammarNote:
						'Short time words often come at the start of the sentence: "Ngayon..." for today, "Bukas..." for tomorrow.',
					color: 'from-yellow-400 to-lime-500',
					introCards: [
						{
							id: 'intro-schedule-1',
							kind: 'word',
							tagalog: 'Ngayon',
							meaning: 'Today / now',
							audioText: 'Ngayon',
							example: '"Ngayon ako pupunta" means "I will go today."',
							emoji: 'Today',
						},
						{
							id: 'intro-schedule-2',
							kind: 'word',
							tagalog: 'Bukas',
							meaning: 'Tomorrow',
							audioText: 'Bukas',
							example: 'Use it for next-day plans.',
							emoji: 'Tomorrow',
						},
						{
							id: 'intro-schedule-3',
							kind: 'word',
							tagalog: 'Mamaya',
							meaning: 'Later',
							audioText: 'Mamaya',
							example: 'Very useful for casual plans.',
							emoji: 'Later',
						},
					],
					matchPairs: [
						{ left: 'today', right: 'Ngayon' },
						{ left: 'tomorrow', right: 'Bukas' },
						{ left: 'later', right: 'Mamaya' },
					],
					buildPrompt: 'Build "I will go tomorrow."',
					buildOptions: ['Bukas', 'ako', 'pupunta', 'ngayon'],
					correctSequence: ['Bukas', 'ako', 'pupunta'],
					blankPrompt: 'Complete the time phrase.',
					sentenceTemplate: '___ ako kakain.',
					acceptableAnswers: ['Mamaya', 'mamaya'],
					placeholder: 'Time word',
					listeningPrompt: 'What time word do you hear?',
					audioText: 'Ngayon',
					listeningOptions: ['today / now', 'tomorrow', 'later'],
					correctAnswer: 'today / now',
					speakingPrompt: 'Say "I will go tomorrow."',
					expectedTranscript: 'Bukas ako pupunta.',
					referenceTranslation: 'I will go tomorrow.',
					finalExercise: 'dictation',
				}),
			],
		},
	],
}
