import type { Unit } from '@/lib/domain/models'

import { createGeneratedLesson } from '@/content/units/unit-helpers'

const unitId = 'unit-06'
const shoppingId = 'unit-06-shopping-basics'
const homeId = 'unit-06-at-home'
const directionsId = 'unit-06-directions'

export const unit06: Unit = {
	id: unitId,
	order: 6,
	title: 'Home and Around Town',
	description:
		'Shopping, home descriptions, locations, directions, and commands.',
	theme: 'Market violet',
	bannerTitle: 'Move through town',
	bannerSubtitle: 'Buy simple items, describe your home, and ask where to go.',
	categories: [
		{
			id: shoppingId,
			unitId,
			order: 1,
			title: 'Shopping Basics',
			subtitle: 'Use numbers and prices',
			description: 'Shop for items using numbers and simple price questions.',
			themeColor: 'from-violet-400 to-purple-500',
			accentColor: 'bg-violet-400',
			icon: 'spark',
			hasGuidebook: true,
			lessons: [
				createGeneratedLesson({
					id: 'lesson-numbers-prices',
					unitId,
					categoryId: shoppingId,
					order: 1,
					title: 'Numbers and Prices',
					subtitle: 'Ask how much',
					description: 'Use small numbers and ask prices while shopping.',
					grammarNote:
						'Use "Magkano ito?" for "How much is this?" and put numbers before the item when counting.',
					color: 'from-violet-400 to-fuchsia-500',
					introCards: [
						{
							id: 'intro-price-1',
							kind: 'phrase',
							tagalog: 'Magkano ito?',
							meaning: 'How much is this?',
							audioText: 'Magkano ito?',
							example: 'One of the most useful shopping questions.',
							emoji: 'Price',
						},
						{
							id: 'intro-price-2',
							kind: 'word',
							tagalog: 'Isa',
							meaning: 'One',
							audioText: 'Isa',
							example: 'Use it to count one item.',
							emoji: 'One',
						},
						{
							id: 'intro-price-3',
							kind: 'word',
							tagalog: 'Dalawa',
							meaning: 'Two',
							audioText: 'Dalawa',
							example: 'Use it to count two items.',
							emoji: 'Two',
						},
					],
					matchPairs: [
						{ left: 'How much is this?', right: 'Magkano ito?' },
						{ left: 'one', right: 'Isa' },
						{ left: 'two', right: 'Dalawa' },
					],
					buildPrompt: 'Build "How much is this?"',
					buildOptions: ['Magkano', 'ito', 'isa', 'dalawa'],
					correctSequence: ['Magkano', 'ito'],
					blankPrompt: 'Complete the number phrase.',
					sentenceTemplate: '___ mansanas.',
					acceptableAnswers: ['Dalawa', 'dalawa'],
					placeholder: 'Number',
					listeningPrompt: 'What shopping question do you hear?',
					audioText: 'Magkano ito?',
					listeningOptions: [
						'How much is this?',
						'Where is this?',
						'I want this',
					],
					correctAnswer: 'How much is this?',
					speakingPrompt: 'Say "How much is this?"',
					expectedTranscript: 'Magkano ito?',
					referenceTranslation: 'How much is this?',
				}),
				createGeneratedLesson({
					id: 'lesson-buy-items',
					unitId,
					categoryId: shoppingId,
					order: 2,
					title: 'Buy Items',
					subtitle: 'Ask for things',
					description: 'Request simple items politely in a shop.',
					grammarNote: 'Use "Pabili po..." to politely ask to buy something.',
					color: 'from-purple-400 to-pink-500',
					introCards: [
						{
							id: 'intro-buy-1',
							kind: 'phrase',
							tagalog: 'Pabili po',
							meaning: 'I would like to buy, please',
							audioText: 'Pabili po',
							example: 'A polite opening at a shop.',
							emoji: 'Buy',
						},
						{
							id: 'intro-buy-2',
							kind: 'word',
							tagalog: 'Tubig',
							meaning: 'Water',
							audioText: 'Tubig',
							example: 'A common thing to buy.',
							emoji: 'Water',
						},
						{
							id: 'intro-buy-3',
							kind: 'phrase',
							tagalog: 'Pabili po ng tubig',
							meaning: 'I would like to buy water, please',
							audioText: 'Pabili po ng tubig',
							example: 'A complete polite shopping request.',
							emoji: 'Request',
						},
					],
					matchPairs: [
						{ left: 'I would like to buy, please', right: 'Pabili po' },
						{ left: 'water', right: 'Tubig' },
						{ left: 'I would like to buy water', right: 'Pabili po ng tubig' },
					],
					buildPrompt: 'Build "I would like to buy water, please."',
					buildOptions: ['Pabili', 'po', 'ng', 'tubig', 'ito'],
					correctSequence: ['Pabili', 'po', 'ng', 'tubig'],
					blankPrompt: 'Complete the shop request.',
					sentenceTemplate: 'Pabili po ng ___.',
					acceptableAnswers: ['tubig', 'Tubig'],
					placeholder: 'Item',
					listeningPrompt: 'What does the customer want?',
					audioText: 'Pabili po ng tubig',
					listeningOptions: ['water', 'rice', 'coffee'],
					correctAnswer: 'water',
					speakingPrompt: 'Say "I would like to buy water, please."',
					expectedTranscript: 'Pabili po ng tubig.',
					referenceTranslation: 'I would like to buy water, please.',
					finalExercise: 'listen-repeat',
				}),
			],
		},
		{
			id: homeId,
			unitId,
			order: 2,
			title: 'At Home',
			subtitle: 'Rooms and locations',
			description: 'Describe your house and specify where things are located.',
			themeColor: 'from-blue-400 to-indigo-500',
			accentColor: 'bg-blue-400',
			icon: 'guidebook',
			lessons: [
				createGeneratedLesson({
					id: 'lesson-describe-house',
					unitId,
					categoryId: homeId,
					order: 1,
					title: 'Describe Your House',
					subtitle: 'Name rooms',
					description: 'Use basic home and room words.',
					grammarNote:
						'Use "May..." for "There is/are..." when describing what your home has.',
					color: 'from-blue-400 to-sky-500',
					introCards: [
						{
							id: 'intro-house-1',
							kind: 'word',
							tagalog: 'Kusina',
							meaning: 'Kitchen',
							audioText: 'Kusina',
							example: 'A key room word.',
							emoji: 'Kitchen',
						},
						{
							id: 'intro-house-2',
							kind: 'word',
							tagalog: 'Kuwarto',
							meaning: 'Bedroom / room',
							audioText: 'Kuwarto',
							example: 'A common home word.',
							emoji: 'Room',
						},
						{
							id: 'intro-house-3',
							kind: 'phrase',
							tagalog: 'May kusina',
							meaning: 'There is a kitchen',
							audioText: 'May kusina',
							example: 'Use it to describe a home.',
							emoji: 'Home',
						},
					],
					matchPairs: [
						{ left: 'kitchen', right: 'Kusina' },
						{ left: 'bedroom / room', right: 'Kuwarto' },
						{ left: 'there is a kitchen', right: 'May kusina' },
					],
					buildPrompt: 'Build "There is a kitchen."',
					buildOptions: ['May', 'kusina', 'kuwarto', 'ako'],
					correctSequence: ['May', 'kusina'],
					blankPrompt: 'Complete the home sentence.',
					sentenceTemplate: 'May ___ sa bahay.',
					acceptableAnswers: ['kuwarto', 'Kuwarto'],
					placeholder: 'Room',
					listeningPrompt: 'Which room do you hear?',
					audioText: 'Kusina',
					listeningOptions: ['kitchen', 'bedroom', 'store'],
					correctAnswer: 'kitchen',
					speakingPrompt: 'Say "There is a kitchen."',
					expectedTranscript: 'May kusina.',
					referenceTranslation: 'There is a kitchen.',
				}),
				createGeneratedLesson({
					id: 'lesson-where-things-are',
					unitId,
					categoryId: homeId,
					order: 2,
					title: 'Where Things Are',
					subtitle: 'Locate objects',
					description: 'Say where things are with simple location words.',
					grammarNote: 'Use "Nasa..." for "is/are at/in/on" before a place.',
					color: 'from-sky-400 to-cyan-500',
					introCards: [
						{
							id: 'intro-location-1',
							kind: 'word',
							tagalog: 'Nasa',
							meaning: 'At / in / on',
							audioText: 'Nasa',
							example: '"Nasa mesa" means "on/at the table."',
							emoji: 'At',
						},
						{
							id: 'intro-location-2',
							kind: 'phrase',
							tagalog: 'Nasa mesa',
							meaning: 'On the table',
							audioText: 'Nasa mesa',
							example: 'Useful when looking for things.',
							emoji: 'Table',
						},
						{
							id: 'intro-location-3',
							kind: 'word',
							tagalog: 'Susi',
							meaning: 'Key',
							audioText: 'Susi',
							example: 'A common object to locate.',
							emoji: 'Key',
						},
					],
					matchPairs: [
						{ left: 'at / in / on', right: 'Nasa' },
						{ left: 'on the table', right: 'Nasa mesa' },
						{ left: 'key', right: 'Susi' },
					],
					buildPrompt: 'Build "The key is on the table."',
					buildOptions: ['Nasa', 'mesa', 'ang', 'susi', 'bahay'],
					correctSequence: ['Nasa', 'mesa', 'ang', 'susi'],
					blankPrompt: 'Complete the location.',
					sentenceTemplate: 'Nasa ___ ang susi.',
					acceptableAnswers: ['mesa', 'Mesa'],
					placeholder: 'Place',
					listeningPrompt: 'Where is it?',
					audioText: 'Nasa mesa ang susi',
					listeningOptions: [
						'The key is on the table',
						'The key is in the store',
						'The key is at school',
					],
					correctAnswer: 'The key is on the table',
					speakingPrompt: 'Say "The key is on the table."',
					expectedTranscript: 'Nasa mesa ang susi.',
					referenceTranslation: 'The key is on the table.',
					finalExercise: 'dictation',
				}),
			],
		},
		{
			id: directionsId,
			unitId,
			order: 3,
			title: 'Directions',
			subtitle: 'Ask where to go',
			description:
				'Give and ask for directions with simple requests and commands.',
			themeColor: 'from-emerald-400 to-teal-500',
			accentColor: 'bg-emerald-400',
			icon: 'trophy',
			hasRewardChest: true,
			lessons: [
				createGeneratedLesson({
					id: 'lesson-ask-directions',
					unitId,
					categoryId: directionsId,
					order: 1,
					title: 'Ask Directions',
					subtitle: 'Find a place',
					description: 'Ask where common places are.',
					grammarNote: 'Use "Nasaan ang..." to ask "Where is the...?"',
					color: 'from-emerald-400 to-green-500',
					introCards: [
						{
							id: 'intro-dir-1',
							kind: 'phrase',
							tagalog: 'Nasaan ang tindahan?',
							meaning: 'Where is the store?',
							audioText: 'Nasaan ang tindahan?',
							example: 'A direct direction question.',
							emoji: 'Where',
						},
						{
							id: 'intro-dir-2',
							kind: 'word',
							tagalog: 'Kaliwa',
							meaning: 'Left',
							audioText: 'Kaliwa',
							example: 'A useful direction word.',
							emoji: 'Left',
						},
						{
							id: 'intro-dir-3',
							kind: 'word',
							tagalog: 'Kanan',
							meaning: 'Right',
							audioText: 'Kanan',
							example: 'A useful direction word.',
							emoji: 'Right',
						},
					],
					matchPairs: [
						{ left: 'Where is the store?', right: 'Nasaan ang tindahan?' },
						{ left: 'left', right: 'Kaliwa' },
						{ left: 'right', right: 'Kanan' },
					],
					buildPrompt: 'Build "Where is the store?"',
					buildOptions: ['Nasaan', 'ang', 'tindahan', 'kanan'],
					correctSequence: ['Nasaan', 'ang', 'tindahan'],
					blankPrompt: 'Complete the direction word.',
					sentenceTemplate: 'Sa ___ ka lumiko.',
					acceptableAnswers: ['kanan', 'Kanan'],
					placeholder: 'Direction',
					listeningPrompt: 'What question do you hear?',
					audioText: 'Nasaan ang tindahan?',
					listeningOptions: [
						'Where is the store?',
						'Where is the house?',
						'Turn right',
					],
					correctAnswer: 'Where is the store?',
					speakingPrompt: 'Say "Where is the store?"',
					expectedTranscript: 'Nasaan ang tindahan?',
					referenceTranslation: 'Where is the store?',
				}),
				createGeneratedLesson({
					id: 'lesson-simple-commands',
					unitId,
					categoryId: directionsId,
					order: 2,
					title: 'Simple Commands',
					subtitle: 'Give clear directions',
					description: 'Use polite commands for moving around town.',
					grammarNote:
						'Commands like "Lumiko" and "Dumiretso" are useful on their own, and "po" softens them.',
					color: 'from-teal-400 to-cyan-500',
					introCards: [
						{
							id: 'intro-command-1',
							kind: 'word',
							tagalog: 'Dumiretso',
							meaning: 'Go straight',
							audioText: 'Dumiretso',
							example: 'A simple direction command.',
							emoji: 'Straight',
						},
						{
							id: 'intro-command-2',
							kind: 'word',
							tagalog: 'Lumiko',
							meaning: 'Turn',
							audioText: 'Lumiko',
							example: 'Pair it with left or right.',
							emoji: 'Turn',
						},
						{
							id: 'intro-command-3',
							kind: 'phrase',
							tagalog: 'Dumiretso po kayo',
							meaning: 'Please go straight',
							audioText: 'Dumiretso po kayo',
							example: 'A polite direction.',
							emoji: 'Please',
						},
					],
					matchPairs: [
						{ left: 'go straight', right: 'Dumiretso' },
						{ left: 'turn', right: 'Lumiko' },
						{ left: 'please go straight', right: 'Dumiretso po kayo' },
					],
					buildPrompt: 'Build "Please go straight."',
					buildOptions: ['Dumiretso', 'po', 'kayo', 'Lumiko'],
					correctSequence: ['Dumiretso', 'po', 'kayo'],
					blankPrompt: 'Complete the command.',
					sentenceTemplate: '___ sa kaliwa.',
					acceptableAnswers: ['Lumiko', 'lumiko'],
					placeholder: 'Command',
					listeningPrompt: 'What command do you hear?',
					audioText: 'Dumiretso po kayo',
					listeningOptions: [
						'Please go straight',
						'Please turn left',
						'Please stop',
					],
					correctAnswer: 'Please go straight',
					speakingPrompt: 'Say "Turn left."',
					expectedTranscript: 'Lumiko sa kaliwa.',
					referenceTranslation: 'Turn left.',
					finalExercise: 'listen-repeat',
				}),
			],
		},
	],
}
