import type { Unit } from "@/lib/domain/models"

export const unit01: Unit = {
  id: "unit-01",
  order: 1,
  title: "Warm Hellos",
  description: "Greetings, courtesy phrases, and simple conversational starts.",
  theme: "Sunrise orange",
  bannerTitle: "Start everyday greetings",
  bannerSubtitle: "Say hello, respond politely, and sound natural right away.",
  categories: [
    {
      id: "unit-01-greetings",
      unitId: "unit-01",
      order: 1,
      title: "Greeting Lane",
      subtitle: "Say hello naturally",
      description: "Warm up with common greetings and easy replies.",
      themeColor: "from-lime-400 to-green-500",
      accentColor: "bg-lime-400",
      icon: "guidebook",
      hasGuidebook: true,
      lessons: [
        {
          id: "lesson-greetings",
          unitId: "unit-01",
          categoryId: "unit-01-greetings",
          order: 1,
          title: "Greetings",
          subtitle: "Say hello naturally",
          description: "Practice the most common Tagalog greetings and polite replies.",
          grammarNote:
            "Tagalog greetings are often short and friendly. You will hear both formal and casual versions, so focus on common phrases first.",
          color: "from-orange-400 to-pink-400",
          introCards: [
            {
              id: "intro-greetings-1",
              kind: "phrase",
              tagalog: "Magandang umaga",
              meaning: "Good morning",
              audioText: "Magandang umaga",
              example: "Use it to greet someone early in the day.",
              emoji: "Sunrise",
            },
            {
              id: "intro-greetings-2",
              kind: "word",
              tagalog: "Kamusta",
              meaning: "Hello / How are you?",
              audioText: "Kamusta",
              example: "A friendly everyday greeting.",
              emoji: "Wave",
            },
            {
              id: "intro-greetings-3",
              kind: "word",
              tagalog: "Salamat",
              meaning: "Thank you",
              audioText: "Salamat",
              example: "You will use this all the time.",
              emoji: "Thanks",
            },
          ],
          exercises: [
            {
              id: "greet-1",
              type: "tap-translation",
              prompt: 'Build "Good morning."',
              instructions: "Tap the tiles in order.",
              xp: 5,
              options: [
                { id: "magandang", label: "Magandang", value: "Magandang" },
                { id: "umaga", label: "umaga", value: "umaga" },
                { id: "salamat", label: "salamat", value: "salamat" },
              ],
              correctSequence: ["Magandang", "umaga"],
              vocabularyFocus: ["magandang", "umaga"],
            },
            {
              id: "greet-2",
              type: "word-matching",
              prompt: "Match the greeting pairs.",
              instructions: "Tap matching pairs.",
              xp: 5,
              pairs: [
                { left: "Hello", right: "Kamusta" },
                { left: "Good evening", right: "Magandang gabi" },
                { left: "Thank you", right: "Salamat" },
              ],
            },
            {
              id: "greet-3",
              type: "listening-mcq",
              prompt: "What do you hear?",
              instructions: "Listen, then choose the meaning.",
              xp: 6,
              audioText: "Magandang hapon",
              options: [
                { id: "a", label: "Good afternoon", value: "Good afternoon" },
                { id: "b", label: "Good night", value: "Good night" },
                { id: "c", label: "Thank you", value: "Thank you" },
              ],
              correctAnswer: "Good afternoon",
            },
            {
              id: "greet-4",
              type: "dictation",
              prompt: "Type what you hear.",
              instructions: "Listen and write the Tagalog phrase.",
              xp: 7,
              audioText: "Salamat po",
              acceptableAnswers: ["Salamat po", "salamat po"],
              helperText: '"Po" adds politeness.',
            },
            {
              id: "greet-5",
              type: "listen-repeat",
              prompt: "Listen and repeat the phrase.",
              instructions: "Use your voice or type what you said.",
              xp: 8,
              audioText: "Kamusta ka?",
              expectedTranscript: "Kamusta ka?",
              helperText: 'This means "How are you?"',
            },
          ],
        },
        {
          id: "lesson-time-greetings",
          unitId: "unit-01",
          categoryId: "unit-01-greetings",
          order: 2,
          title: "Times of Day",
          subtitle: "Use the right greeting",
          description: "Match morning, afternoon, and evening greetings to the moment.",
          grammarNote:
            'Many greetings start with "Magandang" plus the time of day. Learn those chunks as one piece.',
          color: "from-yellow-400 to-orange-500",
          introCards: [
            {
              id: "intro-time-1",
              kind: "phrase",
              tagalog: "Magandang hapon",
              meaning: "Good afternoon",
              audioText: "Magandang hapon",
              example: "Use it after lunch and before evening.",
              emoji: "Sun",
            },
            {
              id: "intro-time-2",
              kind: "phrase",
              tagalog: "Magandang gabi",
              meaning: "Good evening",
              audioText: "Magandang gabi",
              example: "A warm greeting once it is evening.",
              emoji: "Moon",
            },
            {
              id: "intro-time-3",
              kind: "word",
              tagalog: "Gabi",
              meaning: "Night / evening",
              audioText: "Gabi",
              example: "You will hear it inside evening greetings.",
              emoji: "Night",
            },
          ],
          exercises: [
            {
              id: "time-greet-1",
              type: "word-matching",
              prompt: "Match the time-based greetings.",
              instructions: "Connect the English and Tagalog phrases.",
              xp: 5,
              pairs: [
                { left: "Good morning", right: "Magandang umaga" },
                { left: "Good afternoon", right: "Magandang hapon" },
                { left: "Good evening", right: "Magandang gabi" },
              ],
            },
            {
              id: "time-greet-2",
              type: "tap-translation",
              prompt: 'Build "Good evening."',
              instructions: "Tap the tiles in order.",
              xp: 6,
              options: [
                { id: "magandang", label: "Magandang", value: "Magandang" },
                { id: "gabi", label: "gabi", value: "gabi" },
                { id: "umaga", label: "umaga", value: "umaga" },
              ],
              correctSequence: ["Magandang", "gabi"],
            },
            {
              id: "time-greet-3",
              type: "listening-mcq",
              prompt: "Choose the greeting you hear.",
              instructions: "Listen for the time word.",
              xp: 6,
              audioText: "Magandang gabi",
              options: [
                { id: "a", label: "Good evening", value: "Good evening" },
                { id: "b", label: "Good afternoon", value: "Good afternoon" },
                { id: "c", label: "Good morning", value: "Good morning" },
              ],
              correctAnswer: "Good evening",
            },
            {
              id: "time-greet-4",
              type: "fill-in-the-blank",
              prompt: "Complete the greeting.",
              instructions: "Type the missing word.",
              xp: 6,
              sentenceTemplate: "Magandang ___.",
              acceptableAnswers: ["hapon", "Hapon"],
              placeholder: "Missing time word",
            },
            {
              id: "time-greet-5",
              type: "speaking-prompt",
              prompt: 'Say "Good afternoon."',
              instructions: "Speak in Tagalog or type your best attempt.",
              xp: 8,
              expectedTranscript: "Magandang hapon.",
              referenceTranslation: "Good afternoon.",
            },
          ],
        },
        {
          id: "lesson-easy-replies",
          unitId: "unit-01",
          categoryId: "unit-01-greetings",
          order: 3,
          title: "Easy Replies",
          subtitle: "Answer warmly",
          description: "Reply to greetings with simple friendly phrases.",
          grammarNote:
            "Small replies keep conversations moving. Short answers are natural and useful in early conversations.",
          color: "from-pink-400 to-rose-500",
          introCards: [
            {
              id: "intro-reply-1",
              kind: "phrase",
              tagalog: "Mabuti naman",
              meaning: "I am good / doing well",
              audioText: "Mabuti naman",
              example: 'A soft, common reply to "How are you?"',
              emoji: "Smile",
            },
            {
              id: "intro-reply-2",
              kind: "phrase",
              tagalog: "Ayos lang",
              meaning: "I am okay",
              audioText: "Ayos lang",
              example: "Useful when you want a casual neutral answer.",
              emoji: "Okay",
            },
            {
              id: "intro-reply-3",
              kind: "word",
              tagalog: "Naman",
              meaning: "softening reply word",
              audioText: "Naman",
              example: "It helps your reply sound natural and conversational.",
              emoji: "Chat",
            },
          ],
          exercises: [
            {
              id: "reply-1",
              type: "sentence-reorder",
              prompt: 'Reorder "I am okay."',
              instructions: "Arrange the words.",
              xp: 6,
              tokens: ["lang", "Ayos"],
              correctSequence: ["Ayos", "lang"],
            },
            {
              id: "reply-2",
              type: "word-matching",
              prompt: "Match the reply meanings.",
              instructions: "Pair phrase and meaning.",
              xp: 5,
              pairs: [
                { left: "I am good", right: "Mabuti naman" },
                { left: "I am okay", right: "Ayos lang" },
                { left: "Thank you", right: "Salamat" },
              ],
            },
            {
              id: "reply-3",
              type: "dictation",
              prompt: "Type the reply you hear.",
              instructions: "Listen and write the phrase.",
              xp: 7,
              audioText: "Mabuti naman",
              acceptableAnswers: ["Mabuti naman", "mabuti naman"],
            },
            {
              id: "reply-4",
              type: "tap-translation",
              prompt: 'Build "I am good."',
              instructions: "Tap the tiles in order.",
              xp: 6,
              options: [
                { id: "mabuti", label: "Mabuti", value: "Mabuti" },
                { id: "naman", label: "naman", value: "naman" },
                { id: "gabi", label: "gabi", value: "gabi" },
              ],
              correctSequence: ["Mabuti", "naman"],
            },
            {
              id: "reply-5",
              type: "listen-repeat",
              prompt: "Repeat the reply.",
              instructions: "Listen and echo it back.",
              xp: 8,
              audioText: "Ayos lang",
              expectedTranscript: "Ayos lang",
            },
          ],
        },
      ],
    },
    {
      id: "unit-01-courtesy",
      unitId: "unit-01",
      order: 2,
      title: "Courtesy Path",
      subtitle: "Friendly polite phrases",
      description: "Add the little words that make Tagalog sound respectful and warm.",
      themeColor: "from-yellow-400 to-orange-500",
      accentColor: "bg-yellow-400",
      icon: "trophy",
      hasRewardChest: true,
      lessons: [
        {
          id: "lesson-courtesy",
          unitId: "unit-01",
          categoryId: "unit-01-courtesy",
          order: 1,
          title: "Courtesy",
          subtitle: "Friendly polite phrases",
          description: "Use polite responses and light small talk.",
          grammarNote:
            'Words like "po" and "opo" make speech respectful. They often appear in replies to older people or in polite situations.',
          color: "from-amber-400 to-orange-500",
          introCards: [
            {
              id: "intro-courtesy-1",
              kind: "word",
              tagalog: "Opo",
              meaning: "Yes (polite)",
              audioText: "Opo",
              example: "A respectful yes for older people or formal situations.",
              emoji: "Respect",
            },
            {
              id: "intro-courtesy-2",
              kind: "phrase",
              tagalog: "Walang anuman",
              meaning: "You are welcome",
              audioText: "Walang anuman",
              example: "A kind reply after someone says thank you.",
              emoji: "Smile",
            },
            {
              id: "intro-courtesy-3",
              kind: "word",
              tagalog: "Po",
              meaning: "Polite particle",
              audioText: "Po",
              example: 'Add "po" to sound respectful.',
              emoji: "Spark",
            },
          ],
          exercises: [
            {
              id: "courtesy-1",
              type: "sentence-reorder",
              prompt: 'Reorder to say "Thank you very much."',
              instructions: "Put the words in the right order.",
              xp: 6,
              tokens: ["marami", "Salamat", "po"],
              correctSequence: ["Salamat", "po", "marami"],
            },
            {
              id: "courtesy-2",
              type: "fill-in-the-blank",
              prompt: "Complete the polite reply.",
              instructions: "Type the missing phrase.",
              xp: 6,
              sentenceTemplate: "___, salamat!",
              acceptableAnswers: ["Walang anuman", "walang anuman"],
              placeholder: "Your answer",
              helperText: 'This means "You are welcome."',
            },
            {
              id: "courtesy-3",
              type: "listening-mcq",
              prompt: "Pick the phrase you hear.",
              instructions: "Listen carefully.",
              xp: 6,
              audioText: "Opo",
              options: [
                { id: "a", label: "Yes (polite)", value: "Yes (polite)" },
                { id: "b", label: "No", value: "No" },
                { id: "c", label: "Maybe", value: "Maybe" },
              ],
              correctAnswer: "Yes (polite)",
            },
            {
              id: "courtesy-4",
              type: "speaking-prompt",
              prompt: 'Say "Thank you."',
              instructions: "Speak in Tagalog or type your best attempt.",
              xp: 8,
              expectedTranscript: "Salamat",
              referenceTranslation: "Thank you",
            },
            {
              id: "courtesy-5",
              type: "tap-translation",
              prompt: 'Build "Yes, ma am / sir."',
              instructions: "Tap the tiles to answer politely.",
              xp: 6,
              options: [
                { id: "opo", label: "Opo", value: "Opo" },
                { id: "hindi", label: "Hindi", value: "Hindi" },
                { id: "po", label: "po", value: "po" },
              ],
              correctSequence: ["Opo"],
            },
          ],
        },
        {
          id: "lesson-polite-requests",
          unitId: "unit-01",
          categoryId: "unit-01-courtesy",
          order: 2,
          title: "Polite Requests",
          subtitle: "Ask nicely",
          description: "Use a few soft request phrases in everyday polite moments.",
          grammarNote:
            'Short request words like "paki" and "pwede" help you sound practical and respectful without long sentences.',
          color: "from-orange-400 to-amber-500",
          introCards: [
            {
              id: "intro-request-1",
              kind: "word",
              tagalog: "Paki",
              meaning: "please do",
              audioText: "Paki",
              example: "Use it before an action when asking someone to do something.",
              emoji: "Ask",
            },
            {
              id: "intro-request-2",
              kind: "word",
              tagalog: "Pwede",
              meaning: "may / can",
              audioText: "Pwede",
              example: "Useful when asking for permission.",
              emoji: "Open",
            },
            {
              id: "intro-request-3",
              kind: "phrase",
              tagalog: "Pwede po ba?",
              meaning: "May I?",
              audioText: "Pwede po ba?",
              example: "A polite way to ask for permission.",
              emoji: "Question",
            },
          ],
          exercises: [
            {
              id: "request-1",
              type: "word-matching",
              prompt: "Match the polite request phrases.",
              instructions: "Pair the English and Tagalog meanings.",
              xp: 5,
              pairs: [
                { left: "May I?", right: "Pwede po ba?" },
                { left: "can / may", right: "Pwede" },
                { left: "please do", right: "Paki" },
              ],
            },
            {
              id: "request-2",
              type: "tap-translation",
              prompt: 'Build "May I?"',
              instructions: "Tap the tiles in order.",
              xp: 6,
              options: [
                { id: "pwede", label: "Pwede", value: "Pwede" },
                { id: "po", label: "po", value: "po" },
                { id: "ba", label: "ba?", value: "ba?" },
              ],
              correctSequence: ["Pwede", "po", "ba?"],
            },
            {
              id: "request-3",
              type: "listening-mcq",
              prompt: "What phrase do you hear?",
              instructions: "Listen for the polite request.",
              xp: 6,
              audioText: "Pwede po ba?",
              options: [
                { id: "a", label: "May I?", value: "May I?" },
                { id: "b", label: "Thank you", value: "Thank you" },
                { id: "c", label: "You are welcome", value: "You are welcome" },
              ],
              correctAnswer: "May I?",
            },
            {
              id: "request-4",
              type: "fill-in-the-blank",
              prompt: "Complete the request.",
              instructions: "Type the missing word.",
              xp: 6,
              sentenceTemplate: "___ po ba?",
              acceptableAnswers: ["Pwede", "pwede"],
              placeholder: "Missing word",
            },
            {
              id: "request-5",
              type: "listen-repeat",
              prompt: "Repeat the polite question.",
              instructions: "Listen and echo it.",
              xp: 8,
              audioText: "Pwede po ba?",
              expectedTranscript: "Pwede po ba?",
            },
          ],
        },
        {
          id: "lesson-polite-small-talk",
          unitId: "unit-01",
          categoryId: "unit-01-courtesy",
          order: 3,
          title: "Polite Small Talk",
          subtitle: "Keep it respectful",
          description: "Combine yes, thanks, and welcome into short respectful exchanges.",
          grammarNote:
            "Politeness often comes from the combination of tone, short reply words, and where you place po.",
          color: "from-yellow-400 to-rose-500",
          introCards: [
            {
              id: "intro-smalltalk-1",
              kind: "phrase",
              tagalog: "Salamat po",
              meaning: "Thank you (polite)",
              audioText: "Salamat po",
              example: "A respectful version of thank you.",
              emoji: "Thanks",
            },
            {
              id: "intro-smalltalk-2",
              kind: "phrase",
              tagalog: "Opo, salamat",
              meaning: "Yes, thank you",
              audioText: "Opo, salamat",
              example: "A small polite answer in daily conversation.",
              emoji: "Kind",
            },
            {
              id: "intro-smalltalk-3",
              kind: "phrase",
              tagalog: "Walang anuman po",
              meaning: "You are welcome (polite)",
              audioText: "Walang anuman po",
              example: "A soft, warm, respectful reply.",
              emoji: "Warm",
            },
          ],
          exercises: [
            {
              id: "smalltalk-1",
              type: "sentence-reorder",
              prompt: 'Reorder "Yes, thank you."',
              instructions: "Put the polite reply together.",
              xp: 6,
              tokens: ["salamat", "Opo,"],
              correctSequence: ["Opo,", "salamat"],
            },
            {
              id: "smalltalk-2",
              type: "word-matching",
              prompt: "Match the polite exchange.",
              instructions: "Pair each phrase and meaning.",
              xp: 5,
              pairs: [
                { left: "Thank you (polite)", right: "Salamat po" },
                { left: "Yes, thank you", right: "Opo, salamat" },
                { left: "You are welcome (polite)", right: "Walang anuman po" },
              ],
            },
            {
              id: "smalltalk-3",
              type: "dictation",
              prompt: "Type what you hear.",
              instructions: "Write the respectful phrase.",
              xp: 7,
              audioText: "Salamat po",
              acceptableAnswers: ["Salamat po", "salamat po"],
            },
            {
              id: "smalltalk-4",
              type: "tap-translation",
              prompt: 'Build "You are welcome."',
              instructions: "Tap the words in order.",
              xp: 6,
              options: [
                { id: "walang", label: "Walang", value: "Walang" },
                { id: "anuman", label: "anuman", value: "anuman" },
                { id: "opo", label: "Opo", value: "Opo" },
              ],
              correctSequence: ["Walang", "anuman"],
            },
            {
              id: "smalltalk-5",
              type: "speaking-prompt",
              prompt: 'Say "Thank you (polite)."',
              instructions: "Speak or type the phrase.",
              xp: 8,
              expectedTranscript: "Salamat po.",
              referenceTranslation: "Thank you (polite).",
            },
          ],
        },
      ],
    },
  ],
}
