import type { Unit } from "@/lib/domain/models"

export const unit03: Unit = {
  id: "unit-03",
  order: 3,
  title: "Daily Basics",
  description: "Basic nouns, common verbs, and useful simple sentences.",
  theme: "Leaf green",
  bannerTitle: "Handle everyday basics",
  bannerSubtitle: "Learn useful nouns and verbs for simple daily conversations.",
  categories: [
    {
      id: "unit-03-nouns",
      unitId: "unit-03",
      order: 1,
      title: "Noun Garden",
      subtitle: "Useful everyday nouns",
      description: "Recognize common people, objects, and places quickly.",
      themeColor: "from-lime-400 to-green-500",
      accentColor: "bg-lime-400",
      icon: "spark",
      hasGuidebook: true,
      lessons: [
        {
          id: "lesson-nouns",
          unitId: "unit-03",
          categoryId: "unit-03-nouns",
          order: 1,
          title: "People & Things",
          subtitle: "Useful everyday nouns",
          description: "Recognize common people, places, and objects.",
          grammarNote:
            "Common nouns are easy to mix into simple phrases right away. Learn them as chunks you can use in conversation.",
          color: "from-lime-400 to-emerald-500",
          introCards: [
            {
              id: "intro-nouns-1",
              kind: "word",
              tagalog: "Bahay",
              meaning: "House",
              audioText: "Bahay",
              example: '"Ito ang bahay ko" means "This is my house."',
              emoji: "House",
            },
            {
              id: "intro-nouns-2",
              kind: "word",
              tagalog: "Kaibigan",
              meaning: "Friend",
              audioText: "Kaibigan",
              example: "A useful word when talking about people in your life.",
              emoji: "Friend",
            },
            {
              id: "intro-nouns-3",
              kind: "word",
              tagalog: "Pagkain",
              meaning: "Food",
              audioText: "Pagkain",
              example: '"Ito ay pagkain" means "This is food."',
              emoji: "Food",
            },
          ],
          exercises: [
            {
              id: "noun-1",
              type: "word-matching",
              prompt: "Match the everyday words.",
              instructions: "Pair the nouns.",
              xp: 5,
              pairs: [
                { left: "House", right: "Bahay" },
                { left: "Friend", right: "Kaibigan" },
                { left: "Food", right: "Pagkain" },
              ],
            },
            {
              id: "noun-2",
              type: "tap-translation",
              prompt: 'Build "This is food."',
              instructions: "Tap the phrase.",
              xp: 6,
              options: [
                { id: "ito", label: "Ito", value: "Ito" },
                { id: "ay", label: "ay", value: "ay" },
                { id: "pagkain", label: "pagkain", value: "pagkain" },
                { id: "bahay", label: "bahay", value: "bahay" },
              ],
              correctSequence: ["Ito", "ay", "pagkain"],
            },
            {
              id: "noun-3",
              type: "fill-in-the-blank",
              prompt: "Complete the sentence.",
              instructions: "Type the missing noun.",
              xp: 6,
              sentenceTemplate: "Siya ay aking kaibigan sa ___",
              acceptableAnswers: ["bahay", "Bahay"],
              placeholder: "Missing noun",
            },
            {
              id: "noun-4",
              type: "listening-mcq",
              prompt: "What word do you hear?",
              instructions: "Listen and choose.",
              xp: 6,
              audioText: "Kaibigan",
              options: [
                { id: "a", label: "Friend", value: "Friend" },
                { id: "b", label: "Food", value: "Food" },
                { id: "c", label: "School", value: "School" },
              ],
              correctAnswer: "Friend",
            },
            {
              id: "noun-5",
              type: "speaking-prompt",
              prompt: 'Say "This is my house."',
              instructions: "Speak or type the phrase.",
              xp: 8,
              expectedTranscript: "Ito ang bahay ko.",
              referenceTranslation: "This is my house.",
            },
          ],
        },
        {
          id: "lesson-places",
          unitId: "unit-03",
          categoryId: "unit-03-nouns",
          order: 2,
          title: "Places Around You",
          subtitle: "Name useful places",
          description: "Build vocabulary for school, home, and common places around you.",
          grammarNote:
            "Place words are especially useful when paired with simple sentences like 'Ito ang ...' or 'Nasa ...'.",
          color: "from-green-400 to-teal-500",
          introCards: [
            {
              id: "intro-places-1",
              kind: "word",
              tagalog: "Paaralan",
              meaning: "School",
              audioText: "Paaralan",
              example: '"Ito ang paaralan." means "This is the school."',
              emoji: "School",
            },
            {
              id: "intro-places-2",
              kind: "word",
              tagalog: "Tindahan",
              meaning: "Store",
              audioText: "Tindahan",
              example: "A useful place word in everyday errands.",
              emoji: "Store",
            },
            {
              id: "intro-places-3",
              kind: "word",
              tagalog: "Silid",
              meaning: "Room",
              audioText: "Silid",
              example: "Useful for describing parts of a home or school.",
              emoji: "Room",
            },
          ],
          exercises: [
            {
              id: "places-1",
              type: "word-matching",
              prompt: "Match the place words.",
              instructions: "Pair English and Tagalog.",
              xp: 5,
              pairs: [
                { left: "School", right: "Paaralan" },
                { left: "Store", right: "Tindahan" },
                { left: "Room", right: "Silid" },
              ],
            },
            {
              id: "places-2",
              type: "tap-translation",
              prompt: 'Build "This is the school."',
              instructions: "Tap the phrase in order.",
              xp: 6,
              options: [
                { id: "ito", label: "Ito", value: "Ito" },
                { id: "ang", label: "ang", value: "ang" },
                { id: "paaralan", label: "paaralan", value: "paaralan" },
                { id: "silid", label: "silid", value: "silid" },
              ],
              correctSequence: ["Ito", "ang", "paaralan"],
            },
            {
              id: "places-3",
              type: "listening-mcq",
              prompt: "Choose the word you hear.",
              instructions: "Listen for the place word.",
              xp: 6,
              audioText: "Tindahan",
              options: [
                { id: "a", label: "Store", value: "Store" },
                { id: "b", label: "School", value: "School" },
                { id: "c", label: "Friend", value: "Friend" },
              ],
              correctAnswer: "Store",
            },
            {
              id: "places-4",
              type: "fill-in-the-blank",
              prompt: "Complete the phrase.",
              instructions: "Type the missing place word.",
              xp: 6,
              sentenceTemplate: "Ito ang ___.",
              acceptableAnswers: ["silid", "Silid"],
              placeholder: "Missing place word",
            },
            {
              id: "places-5",
              type: "listen-repeat",
              prompt: "Repeat the place phrase.",
              instructions: "Listen and echo it.",
              xp: 8,
              audioText: "Ito ang paaralan",
              expectedTranscript: "Ito ang paaralan",
            },
          ],
        },
        {
          id: "lesson-people-objects",
          unitId: "unit-03",
          categoryId: "unit-03-nouns",
          order: 3,
          title: "People and Objects",
          subtitle: "Spot common things",
          description: "Round out the noun set with a few more useful people and object words.",
          grammarNote:
            "Nouns become more memorable when you connect them to simple real-life scenes rather than isolated lists.",
          color: "from-emerald-400 to-lime-500",
          introCards: [
            {
              id: "intro-obj-1",
              kind: "word",
              tagalog: "Guro",
              meaning: "Teacher",
              audioText: "Guro",
              example: "A helpful person word for school conversations.",
              emoji: "Teacher",
            },
            {
              id: "intro-obj-2",
              kind: "word",
              tagalog: "Mesa",
              meaning: "Table",
              audioText: "Mesa",
              example: "A common borrowed everyday noun.",
              emoji: "Table",
            },
            {
              id: "intro-obj-3",
              kind: "word",
              tagalog: "Bag",
              meaning: "Bag",
              audioText: "Bag",
              example: "Another practical daily word you will hear often.",
              emoji: "Bag",
            },
          ],
          exercises: [
            {
              id: "obj-1",
              type: "sentence-reorder",
              prompt: 'Reorder "This is a table."',
              instructions: "Put the phrase together.",
              xp: 6,
              tokens: ["ang", "Ito", "mesa"],
              correctSequence: ["Ito", "ang", "mesa"],
            },
            {
              id: "obj-2",
              type: "word-matching",
              prompt: "Match the new noun set.",
              instructions: "Pair each noun and meaning.",
              xp: 5,
              pairs: [
                { left: "Teacher", right: "Guro" },
                { left: "Table", right: "Mesa" },
                { left: "Bag", right: "Bag" },
              ],
            },
            {
              id: "obj-3",
              type: "dictation",
              prompt: "Write the word you hear.",
              instructions: "Type the noun.",
              xp: 7,
              audioText: "Guro",
              acceptableAnswers: ["Guro", "guro"],
            },
            {
              id: "obj-4",
              type: "tap-translation",
              prompt: 'Build "bag".',
              instructions: "Tap the correct word.",
              xp: 5,
              options: [
                { id: "bag", label: "Bag", value: "Bag" },
                { id: "mesa", label: "Mesa", value: "Mesa" },
                { id: "guro", label: "Guro", value: "Guro" },
              ],
              correctSequence: ["Bag"],
            },
            {
              id: "obj-5",
              type: "speaking-prompt",
              prompt: 'Say "This is a table."',
              instructions: "Speak or type the phrase.",
              xp: 8,
              expectedTranscript: "Ito ang mesa.",
              referenceTranslation: "This is a table.",
            },
          ],
        },
      ],
    },
    {
      id: "unit-03-verbs",
      unitId: "unit-03",
      order: 2,
      title: "Action Path",
      subtitle: "Talk about daily actions",
      description: "Use simple action phrases for eating, drinking, walking, and studying.",
      themeColor: "from-emerald-400 to-teal-500",
      accentColor: "bg-emerald-400",
      icon: "music",
      hasRewardChest: true,
      lessons: [
        {
          id: "lesson-common-verbs",
          unitId: "unit-03",
          categoryId: "unit-03-verbs",
          order: 1,
          title: "Common Verbs",
          subtitle: "Talk about daily actions",
          description: "Use simple present-like action sentences.",
          grammarNote:
            "You can start with simple action words in context before diving into verb focus systems. The goal here is useful conversation, not perfect grammar coverage.",
          color: "from-emerald-400 to-green-500",
          introCards: [
            {
              id: "intro-verbs-1",
              kind: "word",
              tagalog: "Kumakain",
              meaning: "Eating / eat",
              audioText: "Kumakain",
              example: '"Kumakain ako" means "I eat / I am eating."',
              emoji: "Eat",
            },
            {
              id: "intro-verbs-2",
              kind: "word",
              tagalog: "Umiinom",
              meaning: "Drinking / drink",
              audioText: "Umiinom",
              example: '"Umiinom ako ng tubig" means "I am drinking water."',
              emoji: "Drink",
            },
            {
              id: "intro-verbs-3",
              kind: "word",
              tagalog: "Naglalakad",
              meaning: "Walking / walk",
              audioText: "Naglalakad",
              example: '"Naglalakad siya" means "She is walking."',
              emoji: "Walk",
            },
          ],
          exercises: [
            {
              id: "verb-1",
              type: "sentence-reorder",
              prompt: 'Reorder "I eat."',
              instructions: "Put the words in order.",
              xp: 6,
              tokens: ["ako", "Kumakain"],
              correctSequence: ["Kumakain", "ako"],
            },
            {
              id: "verb-2",
              type: "fill-in-the-blank",
              prompt: "Complete the sentence.",
              instructions: "Type the missing verb.",
              xp: 6,
              sentenceTemplate: "___ ako ng tubig.",
              acceptableAnswers: ["Umiinom", "umiinom"],
              placeholder: "Missing verb",
            },
            {
              id: "verb-3",
              type: "listening-mcq",
              prompt: "Choose the meaning.",
              instructions: "Listen to the verb phrase.",
              xp: 6,
              audioText: "Naglalakad siya",
              options: [
                { id: "a", label: "She is walking", value: "She is walking" },
                { id: "b", label: "She is eating", value: "She is eating" },
                { id: "c", label: "She is drinking", value: "She is drinking" },
              ],
              correctAnswer: "She is walking",
            },
            {
              id: "verb-4",
              type: "dictation",
              prompt: "Write what you hear.",
              instructions: "Type the full sentence.",
              xp: 7,
              audioText: "Nag-aaral ako",
              acceptableAnswers: ["Nag-aaral ako", "Nag aaral ako", "nag-aaral ako"],
            },
            {
              id: "verb-5",
              type: "listen-repeat",
              prompt: "Listen and repeat.",
              instructions: "Say the sentence aloud or type it.",
              xp: 8,
              audioText: "Umiinom ako ng kape",
              expectedTranscript: "Umiinom ako ng kape",
            },
          ],
        },
        {
          id: "lesson-study-and-work",
          unitId: "unit-03",
          categoryId: "unit-03-verbs",
          order: 2,
          title: "Study and Work",
          subtitle: "Talk about what you do",
          description: "Add a few useful action words for studying and working.",
          grammarNote:
            "At this stage, treat the verb as a chunk. You do not need to master the full system to start communicating.",
          color: "from-teal-400 to-cyan-500",
          introCards: [
            {
              id: "intro-study-1",
              kind: "word",
              tagalog: "Nag-aaral",
              meaning: "Studying / study",
              audioText: "Nag-aaral",
              example: '"Nag-aaral ako" means "I am studying."',
              emoji: "Study",
            },
            {
              id: "intro-study-2",
              kind: "word",
              tagalog: "Nagtatrabaho",
              meaning: "Working / work",
              audioText: "Nagtatrabaho",
              example: '"Nagtatrabaho siya" means "He or she is working."',
              emoji: "Work",
            },
            {
              id: "intro-study-3",
              kind: "phrase",
              tagalog: "Nag-aaral ako",
              meaning: "I am studying",
              audioText: "Nag-aaral ako",
              example: "A good daily life sentence.",
              emoji: "Focus",
            },
          ],
          exercises: [
            {
              id: "study-1",
              type: "word-matching",
              prompt: "Match the action words.",
              instructions: "Pair English and Tagalog.",
              xp: 5,
              pairs: [
                { left: "study", right: "Nag-aaral" },
                { left: "work", right: "Nagtatrabaho" },
                { left: "walk", right: "Naglalakad" },
              ],
            },
            {
              id: "study-2",
              type: "tap-translation",
              prompt: 'Build "I am studying."',
              instructions: "Tap the sentence in order.",
              xp: 6,
              options: [
                { id: "nag-aaral", label: "Nag-aaral", value: "Nag-aaral" },
                { id: "ako", label: "ako", value: "ako" },
                { id: "siya", label: "siya", value: "siya" },
              ],
              correctSequence: ["Nag-aaral", "ako"],
            },
            {
              id: "study-3",
              type: "listening-mcq",
              prompt: "What action do you hear?",
              instructions: "Choose the best meaning.",
              xp: 6,
              audioText: "Nagtatrabaho siya",
              options: [
                { id: "a", label: "He or she is working", value: "He or she is working" },
                { id: "b", label: "He or she is drinking", value: "He or she is drinking" },
                { id: "c", label: "He or she is eating", value: "He or she is eating" },
              ],
              correctAnswer: "He or she is working",
            },
            {
              id: "study-4",
              type: "fill-in-the-blank",
              prompt: "Complete the action sentence.",
              instructions: "Type the missing verb.",
              xp: 6,
              sentenceTemplate: "___ ako.",
              acceptableAnswers: ["Nag-aaral", "nag-aaral", "Nag aaral", "nag aaral"],
              placeholder: "Missing verb",
            },
            {
              id: "study-5",
              type: "speaking-prompt",
              prompt: 'Say "I am working."',
              instructions: "Speak or type the phrase.",
              xp: 8,
              expectedTranscript: "Nagtatrabaho ako.",
              referenceTranslation: "I am working.",
            },
          ],
        },
        {
          id: "lesson-daily-actions",
          unitId: "unit-03",
          categoryId: "unit-03-verbs",
          order: 3,
          title: "Daily Actions",
          subtitle: "Build everyday routines",
          description: "Mix a few common actions into short daily routine phrases.",
          grammarNote:
            "Short action phrases become much easier once the verb shapes start to feel familiar through repetition.",
          color: "from-cyan-400 to-emerald-500",
          introCards: [
            {
              id: "intro-daily-1",
              kind: "word",
              tagalog: "Natutulog",
              meaning: "Sleeping / sleep",
              audioText: "Natutulog",
              example: '"Natutulog siya" means "He or she is sleeping."',
              emoji: "Sleep",
            },
            {
              id: "intro-daily-2",
              kind: "word",
              tagalog: "Nagbabasa",
              meaning: "Reading / read",
              audioText: "Nagbabasa",
              example: '"Nagbabasa ako" means "I am reading."',
              emoji: "Read",
            },
            {
              id: "intro-daily-3",
              kind: "phrase",
              tagalog: "Nagbabasa ako",
              meaning: "I am reading",
              audioText: "Nagbabasa ako",
              example: "A useful calm daily-routine line.",
              emoji: "Book",
            },
          ],
          exercises: [
            {
              id: "daily-1",
              type: "sentence-reorder",
              prompt: 'Reorder "I am reading."',
              instructions: "Put the words together.",
              xp: 6,
              tokens: ["ako", "Nagbabasa"],
              correctSequence: ["Nagbabasa", "ako"],
            },
            {
              id: "daily-2",
              type: "word-matching",
              prompt: "Match the daily action words.",
              instructions: "Pair each verb and meaning.",
              xp: 5,
              pairs: [
                { left: "sleep", right: "Natutulog" },
                { left: "read", right: "Nagbabasa" },
                { left: "drink", right: "Umiinom" },
              ],
            },
            {
              id: "daily-3",
              type: "dictation",
              prompt: "Write what you hear.",
              instructions: "Type the full phrase.",
              xp: 7,
              audioText: "Nagbabasa ako",
              acceptableAnswers: ["Nagbabasa ako", "nagbabasa ako"],
            },
            {
              id: "daily-4",
              type: "tap-translation",
              prompt: 'Build "sleep".',
              instructions: "Tap the correct action word.",
              xp: 5,
              options: [
                { id: "natutulog", label: "Natutulog", value: "Natutulog" },
                { id: "nagbabasa", label: "Nagbabasa", value: "Nagbabasa" },
                { id: "kumakain", label: "Kumakain", value: "Kumakain" },
              ],
              correctSequence: ["Natutulog"],
            },
            {
              id: "daily-5",
              type: "listen-repeat",
              prompt: "Repeat the routine phrase.",
              instructions: "Listen and echo it back.",
              xp: 8,
              audioText: "Nagbabasa ako",
              expectedTranscript: "Nagbabasa ako",
            },
          ],
        },
      ],
    },
  ],
}
