import type { Unit } from '@/lib/domain/models'

import { createGeneratedLesson } from '@/content/units/unit-helpers'

const unitId = 'unit-05'
const likesId = 'unit-05-likes-preferences'
const routineId = 'unit-05-daily-routine'
const hobbiesId = 'unit-05-hobbies'

export const unit05: Unit = {
	id: unitId,
	order: 5,
	title: 'Likes and Daily Life',
	description: 'Likes, dislikes, routines, sports, people, and hobbies.',
	theme: 'Blue lagoon',
	bannerTitle: 'Talk about your day',
	bannerSubtitle:
		'Share what you like, what you do, and how you spend free time.',
	categories: [
		{
			id: likesId,
			unitId,
			order: 1,
			title: 'Likes and Preferences',
			subtitle: 'Say what you enjoy',
			description:
				'Express likes, dislikes, favorites, and simple preferences.',
			themeColor: 'from-sky-400 to-cyan-500',
			accentColor: 'bg-sky-400',
			icon: 'star',
			hasGuidebook: true,
			lessons: [
				createGeneratedLesson({
					id: 'lesson-likes-dislikes',
					unitId,
					categoryId: likesId,
					order: 1,
					title: 'Likes and Dislikes',
					subtitle: 'Say what you enjoy',
					description: 'Use simple lines for liking and not liking things.',
					grammarNote:
						'Use "Gusto ko..." for "I like..." and "Ayaw ko..." for "I do not like..." in practical conversation.',
					color: 'from-sky-400 to-blue-500',
					introCards: [
						{
							id: 'intro-like-1',
							kind: 'phrase',
							tagalog: 'Gusto ko ito',
							meaning: 'I like this',
							audioText: 'Gusto ko ito',
							example: 'A quick preference sentence.',
							emoji: 'Like',
						},
						{
							id: 'intro-like-2',
							kind: 'phrase',
							tagalog: 'Ayaw ko nito',
							meaning: 'I do not like this',
							audioText: 'Ayaw ko nito',
							example: 'Useful when choosing between options.',
							emoji: 'Dislike',
						},
						{
							id: 'intro-like-3',
							kind: 'word',
							tagalog: 'Paborito',
							meaning: 'Favorite',
							audioText: 'Paborito',
							example: 'Use it in "Paborito ko ito."',
							emoji: 'Favorite',
						},
					],
					matchPairs: [
						{ left: 'I like this', right: 'Gusto ko ito' },
						{ left: 'I do not like this', right: 'Ayaw ko nito' },
						{ left: 'favorite', right: 'Paborito' },
					],
					buildPrompt: 'Build "I like this."',
					buildOptions: ['Gusto', 'ko', 'ito', 'nito'],
					correctSequence: ['Gusto', 'ko', 'ito'],
					blankPrompt: 'Complete the preference.',
					sentenceTemplate: '___ ko nito.',
					acceptableAnswers: ['Ayaw', 'ayaw'],
					placeholder: 'Dislike word',
					listeningPrompt: 'What does the speaker say?',
					audioText: 'Gusto ko ito',
					listeningOptions: [
						'I like this',
						'I do not like this',
						'This is my favorite',
					],
					correctAnswer: 'I like this',
					speakingPrompt: 'Say "I do not like this."',
					expectedTranscript: 'Ayaw ko nito.',
					referenceTranslation: 'I do not like this.',
				}),
				createGeneratedLesson({
					id: 'lesson-favorite-sports-people',
					unitId,
					categoryId: likesId,
					order: 2,
					title: 'Favorites',
					subtitle: 'Sports and people',
					description: 'Talk about favorite sports and people in simple lines.',
					grammarNote:
						'"Paborito kong..." means "my favorite..." before a noun, while "Paborito ko si..." works for a person.',
					color: 'from-cyan-400 to-teal-500',
					introCards: [
						{
							id: 'intro-favorite-1',
							kind: 'word',
							tagalog: 'Isports',
							meaning: 'Sports',
							audioText: 'Isports',
							example: 'A common borrowed word in everyday speech.',
							emoji: 'Sports',
						},
						{
							id: 'intro-favorite-2',
							kind: 'phrase',
							tagalog: 'Paborito ko si Lea',
							meaning: 'Lea is my favorite',
							audioText: 'Paborito ko si Lea',
							example: 'Use it for a favorite person.',
							emoji: 'Person',
						},
						{
							id: 'intro-favorite-3',
							kind: 'word',
							tagalog: 'Basketbol',
							meaning: 'Basketball',
							audioText: 'Basketbol',
							example: 'A useful sports word.',
							emoji: 'Basketball',
						},
					],
					matchPairs: [
						{ left: 'sports', right: 'Isports' },
						{ left: 'basketball', right: 'Basketbol' },
						{ left: 'Lea is my favorite', right: 'Paborito ko si Lea' },
					],
					buildPrompt: 'Build "I like basketball."',
					buildOptions: ['Gusto', 'ko', 'ang', 'basketbol', 'si'],
					correctSequence: ['Gusto', 'ko', 'ang', 'basketbol'],
					blankPrompt: 'Complete the favorite sentence.',
					sentenceTemplate: 'Paborito ko si ___.',
					acceptableAnswers: ['Lea', 'lea'],
					placeholder: 'Name',
					listeningPrompt: 'What favorite do you hear?',
					audioText: 'Paborito ko si Lea',
					listeningOptions: [
						'Lea is my favorite',
						'Basketball is my favorite',
						'I do not like sports',
					],
					correctAnswer: 'Lea is my favorite',
					speakingPrompt: 'Say "I like basketball."',
					expectedTranscript: 'Gusto ko ang basketbol.',
					referenceTranslation: 'I like basketball.',
					finalExercise: 'listen-repeat',
				}),
			],
		},
		{
			id: routineId,
			unitId,
			order: 2,
			title: 'Daily Routine',
			subtitle: 'Describe your day',
			description: 'Talk about regular actions and time-of-day habits.',
			themeColor: 'from-indigo-400 to-sky-500',
			accentColor: 'bg-indigo-400',
			icon: 'spark',
			lessons: [
				createGeneratedLesson({
					id: 'lesson-morning-routine',
					unitId,
					categoryId: routineId,
					order: 1,
					title: 'Morning Routine',
					subtitle: 'Start the day',
					description: 'Use morning routine verbs in practical sentences.',
					grammarNote: 'Use "Tuwing umaga" for repeated morning habits.',
					color: 'from-indigo-400 to-blue-500',
					introCards: [
						{
							id: 'intro-morning-1',
							kind: 'phrase',
							tagalog: 'Tuwing umaga',
							meaning: 'Every morning',
							audioText: 'Tuwing umaga',
							example: 'A helpful routine phrase.',
							emoji: 'Morning',
						},
						{
							id: 'intro-morning-2',
							kind: 'word',
							tagalog: 'Gumigising',
							meaning: 'Waking up',
							audioText: 'Gumigising',
							example: '"Gumigising ako" means "I wake up."',
							emoji: 'Wake',
						},
						{
							id: 'intro-morning-3',
							kind: 'word',
							tagalog: 'Naliligo',
							meaning: 'Bathing / showering',
							audioText: 'Naliligo',
							example: 'A common daily routine action.',
							emoji: 'Shower',
						},
					],
					matchPairs: [
						{ left: 'every morning', right: 'Tuwing umaga' },
						{ left: 'waking up', right: 'Gumigising' },
						{ left: 'showering', right: 'Naliligo' },
					],
					buildPrompt: 'Build "I wake up every morning."',
					buildOptions: ['Gumigising', 'ako', 'tuwing', 'umaga', 'gabi'],
					correctSequence: ['Gumigising', 'ako', 'tuwing', 'umaga'],
					blankPrompt: 'Complete the routine.',
					sentenceTemplate: '___ ako tuwing umaga.',
					acceptableAnswers: ['Naliligo', 'naliligo'],
					placeholder: 'Action',
					listeningPrompt: 'What action do you hear?',
					audioText: 'Gumigising ako',
					listeningOptions: ['I wake up', 'I sleep', 'I eat'],
					correctAnswer: 'I wake up',
					speakingPrompt: 'Say "I wake up every morning."',
					expectedTranscript: 'Gumigising ako tuwing umaga.',
					referenceTranslation: 'I wake up every morning.',
				}),
				createGeneratedLesson({
					id: 'lesson-evening-routine',
					unitId,
					categoryId: routineId,
					order: 2,
					title: 'Evening Routine',
					subtitle: 'End the day',
					description: 'Talk about evening habits and simple plans.',
					grammarNote:
						'"Sa gabi" means "at night" or "in the evening" and can come at the beginning or end of a sentence.',
					color: 'from-blue-500 to-violet-500',
					introCards: [
						{
							id: 'intro-evening-1',
							kind: 'phrase',
							tagalog: 'Sa gabi',
							meaning: 'At night',
							audioText: 'Sa gabi',
							example: 'A common time phrase.',
							emoji: 'Night',
						},
						{
							id: 'intro-evening-2',
							kind: 'word',
							tagalog: 'Nagpapahinga',
							meaning: 'Resting',
							audioText: 'Nagpapahinga',
							example: '"Nagpapahinga ako" means "I am resting."',
							emoji: 'Rest',
						},
						{
							id: 'intro-evening-3',
							kind: 'phrase',
							tagalog: 'Natutulog ako',
							meaning: 'I sleep',
							audioText: 'Natutulog ako',
							example: 'A simple end-of-day line.',
							emoji: 'Sleep',
						},
					],
					matchPairs: [
						{ left: 'at night', right: 'Sa gabi' },
						{ left: 'resting', right: 'Nagpapahinga' },
						{ left: 'I sleep', right: 'Natutulog ako' },
					],
					buildPrompt: 'Build "I rest at night."',
					buildOptions: ['Nagpapahinga', 'ako', 'sa', 'gabi', 'umaga'],
					correctSequence: ['Nagpapahinga', 'ako', 'sa', 'gabi'],
					blankPrompt: 'Complete the evening sentence.',
					sentenceTemplate: 'Natutulog ako sa ___.',
					acceptableAnswers: ['gabi', 'Gabi'],
					placeholder: 'Time',
					listeningPrompt: 'What does the speaker say?',
					audioText: 'Nagpapahinga ako',
					listeningOptions: ['I am resting', 'I am eating', 'I am leaving'],
					correctAnswer: 'I am resting',
					speakingPrompt: 'Say "I sleep at night."',
					expectedTranscript: 'Natutulog ako sa gabi.',
					referenceTranslation: 'I sleep at night.',
					finalExercise: 'dictation',
				}),
			],
		},
		{
			id: hobbiesId,
			unitId,
			order: 3,
			title: 'Hobbies',
			subtitle: 'Free-time choices',
			description: 'Describe hobbies, leisure activities, and preferences.',
			themeColor: 'from-teal-400 to-emerald-500',
			accentColor: 'bg-teal-400',
			icon: 'music',
			hasRewardChest: true,
			lessons: [
				createGeneratedLesson({
					id: 'lesson-hobbies-leisure',
					unitId,
					categoryId: hobbiesId,
					order: 1,
					title: 'Free Time',
					subtitle: 'Say your hobbies',
					description: 'Talk about simple hobbies and leisure activities.',
					grammarNote:
						'Use "Mahilig ako sa..." for activities you are fond of or often enjoy.',
					color: 'from-teal-400 to-green-500',
					introCards: [
						{
							id: 'intro-hobby-1',
							kind: 'phrase',
							tagalog: 'Mahilig ako sa musika',
							meaning: 'I like music / I am into music',
							audioText: 'Mahilig ako sa musika',
							example: 'A natural way to talk about hobbies.',
							emoji: 'Music',
						},
						{
							id: 'intro-hobby-2',
							kind: 'word',
							tagalog: 'Sayaw',
							meaning: 'Dance',
							audioText: 'Sayaw',
							example: 'Useful for hobbies and performances.',
							emoji: 'Dance',
						},
						{
							id: 'intro-hobby-3',
							kind: 'word',
							tagalog: 'Pagbabasa',
							meaning: 'Reading',
							audioText: 'Pagbabasa',
							example: 'A useful hobby noun.',
							emoji: 'Reading',
						},
					],
					matchPairs: [
						{ left: 'music', right: 'Musika' },
						{ left: 'dance', right: 'Sayaw' },
						{ left: 'reading', right: 'Pagbabasa' },
					],
					buildPrompt: 'Build "I am into music."',
					buildOptions: ['Mahilig', 'ako', 'sa', 'musika', 'sayaw'],
					correctSequence: ['Mahilig', 'ako', 'sa', 'musika'],
					blankPrompt: 'Complete the hobby sentence.',
					sentenceTemplate: 'Mahilig ako sa ___.',
					acceptableAnswers: ['pagbabasa', 'Pagbabasa'],
					placeholder: 'Hobby',
					listeningPrompt: 'What hobby is mentioned?',
					audioText: 'Mahilig ako sa musika',
					listeningOptions: ['music', 'dance', 'sports'],
					correctAnswer: 'music',
					speakingPrompt: 'Say "I am into reading."',
					expectedTranscript: 'Mahilig ako sa pagbabasa.',
					referenceTranslation: 'I am into reading.',
				}),
				createGeneratedLesson({
					id: 'lesson-choosing-activities',
					unitId,
					categoryId: hobbiesId,
					order: 2,
					title: 'Choose Activities',
					subtitle: 'Express preferences',
					description:
						'Choose between activities with simple preference phrases.',
					grammarNote:
						'Use "Mas gusto ko..." for "I prefer..." when choosing one option over another.',
					color: 'from-emerald-400 to-lime-500',
					introCards: [
						{
							id: 'intro-choose-1',
							kind: 'phrase',
							tagalog: 'Mas gusto ko ang sayaw',
							meaning: 'I prefer dance',
							audioText: 'Mas gusto ko ang sayaw',
							example: 'Use it when comparing two choices.',
							emoji: 'Prefer',
						},
						{
							id: 'intro-choose-2',
							kind: 'phrase',
							tagalog: 'Gusto mo ba ng musika?',
							meaning: 'Do you like music?',
							audioText: 'Gusto mo ba ng musika?',
							example: 'A simple yes/no preference question.',
							emoji: 'Question',
						},
						{
							id: 'intro-choose-3',
							kind: 'phrase',
							tagalog: 'Masaya ito',
							meaning: 'This is fun',
							audioText: 'Masaya ito',
							example: 'A quick reaction to an activity.',
							emoji: 'Fun',
						},
					],
					matchPairs: [
						{ left: 'I prefer dance', right: 'Mas gusto ko ang sayaw' },
						{ left: 'Do you like music?', right: 'Gusto mo ba ng musika?' },
						{ left: 'This is fun', right: 'Masaya ito' },
					],
					buildPrompt: 'Build "I prefer dance."',
					buildOptions: ['Mas', 'gusto', 'ko', 'ang', 'sayaw', 'musika'],
					correctSequence: ['Mas', 'gusto', 'ko', 'ang', 'sayaw'],
					blankPrompt: 'Complete the preference question.',
					sentenceTemplate: 'Gusto mo ba ng ___?',
					acceptableAnswers: ['musika', 'Musika'],
					placeholder: 'Activity',
					listeningPrompt: 'What does the speaker prefer?',
					audioText: 'Mas gusto ko ang sayaw',
					listeningOptions: ['dance', 'music', 'reading'],
					correctAnswer: 'dance',
					speakingPrompt: 'Say "This is fun."',
					expectedTranscript: 'Masaya ito.',
					referenceTranslation: 'This is fun.',
					finalExercise: 'listen-repeat',
				}),
			],
		},
	],
}
