import type { Unit } from '@/lib/domain/models'

import { createGeneratedLesson } from '@/content/units/unit-helpers'

const unitId = 'unit-07'
const groceriesId = 'unit-07-groceries'
const restaurantId = 'unit-07-restaurant'
const healthId = 'unit-07-health'

export const unit07: Unit = {
	id: unitId,
	order: 7,
	title: 'Food and Health',
	description: 'Groceries, restaurant orders, symptoms, aches, and remedies.',
	theme: 'Fresh market',
	bannerTitle: 'Eat and feel better',
	bannerSubtitle: 'Shop for food, order politely, and explain simple symptoms.',
	categories: [
		{
			id: groceriesId,
			unitId,
			order: 1,
			title: 'Groceries',
			subtitle: 'Buy food',
			description: 'Shop for groceries with simple food and quantity words.',
			themeColor: 'from-lime-400 to-green-500',
			accentColor: 'bg-lime-400',
			icon: 'spark',
			hasGuidebook: true,
			lessons: [
				createGeneratedLesson({
					id: 'lesson-grocery-foods',
					unitId,
					categoryId: groceriesId,
					order: 1,
					title: 'Grocery Foods',
					subtitle: 'Name market items',
					description: 'Recognize useful grocery words.',
					grammarNote:
						'Use "ng" before the item in many shopping requests: "Pabili po ng bigas."',
					color: 'from-lime-400 to-emerald-500',
					introCards: [
						{
							id: 'intro-grocery-1',
							kind: 'word',
							tagalog: 'Bigas',
							meaning: 'Rice',
							audioText: 'Bigas',
							example: 'A staple grocery word.',
							emoji: 'Rice',
						},
						{
							id: 'intro-grocery-2',
							kind: 'word',
							tagalog: 'Gulay',
							meaning: 'Vegetables',
							audioText: 'Gulay',
							example: 'Useful at markets and restaurants.',
							emoji: 'Vegetables',
						},
						{
							id: 'intro-grocery-3',
							kind: 'word',
							tagalog: 'Prutas',
							meaning: 'Fruit',
							audioText: 'Prutas',
							example: 'A common food category.',
							emoji: 'Fruit',
						},
					],
					matchPairs: [
						{ left: 'rice', right: 'Bigas' },
						{ left: 'vegetables', right: 'Gulay' },
						{ left: 'fruit', right: 'Prutas' },
					],
					buildPrompt: 'Build "I would like to buy rice, please."',
					buildOptions: ['Pabili', 'po', 'ng', 'bigas', 'gulay'],
					correctSequence: ['Pabili', 'po', 'ng', 'bigas'],
					blankPrompt: 'Complete the grocery request.',
					sentenceTemplate: 'Pabili po ng ___.',
					acceptableAnswers: ['gulay', 'Gulay'],
					placeholder: 'Food',
					listeningPrompt: 'Which food word do you hear?',
					audioText: 'Prutas',
					listeningOptions: ['fruit', 'rice', 'vegetables'],
					correctAnswer: 'fruit',
					speakingPrompt: 'Say "I would like to buy rice, please."',
					expectedTranscript: 'Pabili po ng bigas.',
					referenceTranslation: 'I would like to buy rice, please.',
				}),
				createGeneratedLesson({
					id: 'lesson-grocery-quantities',
					unitId,
					categoryId: groceriesId,
					order: 2,
					title: 'Quantities',
					subtitle: 'Ask for amounts',
					description: 'Use simple quantity words when buying groceries.',
					grammarNote:
						'Use "isang kilo" for one kilo and "kalahating kilo" for half a kilo.',
					color: 'from-green-400 to-teal-500',
					introCards: [
						{
							id: 'intro-quantity-1',
							kind: 'phrase',
							tagalog: 'Isang kilo',
							meaning: 'One kilo',
							audioText: 'Isang kilo',
							example: 'Useful at a grocery or market.',
							emoji: 'Kilo',
						},
						{
							id: 'intro-quantity-2',
							kind: 'phrase',
							tagalog: 'Kalahating kilo',
							meaning: 'Half a kilo',
							audioText: 'Kalahating kilo',
							example: 'A practical quantity phrase.',
							emoji: 'Half',
						},
						{
							id: 'intro-quantity-3',
							kind: 'phrase',
							tagalog: 'Isang kilo ng prutas',
							meaning: 'One kilo of fruit',
							audioText: 'Isang kilo ng prutas',
							example: 'Combine quantity and item.',
							emoji: 'Fruit',
						},
					],
					matchPairs: [
						{ left: 'one kilo', right: 'Isang kilo' },
						{ left: 'half a kilo', right: 'Kalahating kilo' },
						{ left: 'one kilo of fruit', right: 'Isang kilo ng prutas' },
					],
					buildPrompt: 'Build "one kilo of fruit."',
					buildOptions: ['Isang', 'kilo', 'ng', 'prutas', 'bigas'],
					correctSequence: ['Isang', 'kilo', 'ng', 'prutas'],
					blankPrompt: 'Complete the quantity phrase.',
					sentenceTemplate: '___ kilo ng bigas.',
					acceptableAnswers: ['Isang', 'isang'],
					placeholder: 'Quantity',
					listeningPrompt: 'What amount do you hear?',
					audioText: 'Kalahating kilo',
					listeningOptions: ['half a kilo', 'one kilo', 'two kilos'],
					correctAnswer: 'half a kilo',
					speakingPrompt: 'Say "one kilo of fruit."',
					expectedTranscript: 'Isang kilo ng prutas.',
					referenceTranslation: 'One kilo of fruit.',
					finalExercise: 'listen-repeat',
				}),
			],
		},
		{
			id: restaurantId,
			unitId,
			order: 2,
			title: 'Restaurant',
			subtitle: 'Order food and drinks',
			description: 'Order food, make requests, and express food preferences.',
			themeColor: 'from-orange-400 to-red-500',
			accentColor: 'bg-orange-400',
			icon: 'chat',
			lessons: [
				createGeneratedLesson({
					id: 'lesson-order-food-drink',
					unitId,
					categoryId: restaurantId,
					order: 1,
					title: 'Order Food',
					subtitle: 'Ask at a restaurant',
					description: 'Order common food and drink politely.',
					grammarNote:
						'Use "Gusto ko ng..." for "I would like..." in simple restaurant orders.',
					color: 'from-orange-400 to-amber-500',
					introCards: [
						{
							id: 'intro-order-1',
							kind: 'phrase',
							tagalog: 'Gusto ko ng kape',
							meaning: 'I would like coffee',
							audioText: 'Gusto ko ng kape',
							example: 'A simple restaurant order.',
							emoji: 'Coffee',
						},
						{
							id: 'intro-order-2',
							kind: 'word',
							tagalog: 'Tubig',
							meaning: 'Water',
							audioText: 'Tubig',
							example: 'Useful for drinks.',
							emoji: 'Water',
						},
						{
							id: 'intro-order-3',
							kind: 'word',
							tagalog: 'Pagkain',
							meaning: 'Food',
							audioText: 'Pagkain',
							example: 'A broad restaurant word.',
							emoji: 'Food',
						},
					],
					matchPairs: [
						{ left: 'I would like coffee', right: 'Gusto ko ng kape' },
						{ left: 'water', right: 'Tubig' },
						{ left: 'food', right: 'Pagkain' },
					],
					buildPrompt: 'Build "I would like coffee."',
					buildOptions: ['Gusto', 'ko', 'ng', 'kape', 'tubig'],
					correctSequence: ['Gusto', 'ko', 'ng', 'kape'],
					blankPrompt: 'Complete the drink order.',
					sentenceTemplate: 'Gusto ko ng ___.',
					acceptableAnswers: ['tubig', 'Tubig'],
					placeholder: 'Drink',
					listeningPrompt: 'What does the speaker want?',
					audioText: 'Gusto ko ng kape',
					listeningOptions: ['coffee', 'water', 'rice'],
					correctAnswer: 'coffee',
					speakingPrompt: 'Say "I would like water."',
					expectedTranscript: 'Gusto ko ng tubig.',
					referenceTranslation: 'I would like water.',
				}),
				createGeneratedLesson({
					id: 'lesson-food-preferences',
					unitId,
					categoryId: restaurantId,
					order: 2,
					title: 'Food Preferences',
					subtitle: 'Choose what tastes good',
					description: 'Express preferences about food and drinks.',
					grammarNote:
						'"Masarap" means delicious, and "maanghang" means spicy.',
					color: 'from-red-400 to-rose-500',
					introCards: [
						{
							id: 'intro-food-pref-1',
							kind: 'word',
							tagalog: 'Masarap',
							meaning: 'Delicious',
							audioText: 'Masarap',
							example: 'A high-value food reaction.',
							emoji: 'Delicious',
						},
						{
							id: 'intro-food-pref-2',
							kind: 'word',
							tagalog: 'Maanghang',
							meaning: 'Spicy',
							audioText: 'Maanghang',
							example: 'Use it when describing food.',
							emoji: 'Spicy',
						},
						{
							id: 'intro-food-pref-3',
							kind: 'phrase',
							tagalog: 'Mas gusto ko ng tubig',
							meaning: 'I prefer water',
							audioText: 'Mas gusto ko ng tubig',
							example: 'A useful restaurant preference.',
							emoji: 'Prefer',
						},
					],
					matchPairs: [
						{ left: 'delicious', right: 'Masarap' },
						{ left: 'spicy', right: 'Maanghang' },
						{ left: 'I prefer water', right: 'Mas gusto ko ng tubig' },
					],
					buildPrompt: 'Build "I prefer water."',
					buildOptions: ['Mas', 'gusto', 'ko', 'ng', 'tubig', 'kape'],
					correctSequence: ['Mas', 'gusto', 'ko', 'ng', 'tubig'],
					blankPrompt: 'Complete the food description.',
					sentenceTemplate: '___ ang pagkain.',
					acceptableAnswers: ['Masarap', 'masarap'],
					placeholder: 'Taste word',
					listeningPrompt: 'What food description do you hear?',
					audioText: 'Maanghang',
					listeningOptions: ['spicy', 'delicious', 'sweet'],
					correctAnswer: 'spicy',
					speakingPrompt: 'Say "The food is delicious."',
					expectedTranscript: 'Masarap ang pagkain.',
					referenceTranslation: 'The food is delicious.',
					finalExercise: 'dictation',
				}),
			],
		},
		{
			id: healthId,
			unitId,
			order: 3,
			title: 'Health',
			subtitle: 'Symptoms and remedies',
			description: 'Describe common symptoms, aches, pains, and remedies.',
			themeColor: 'from-cyan-400 to-blue-500',
			accentColor: 'bg-cyan-400',
			icon: 'trophy',
			hasRewardChest: true,
			lessons: [
				createGeneratedLesson({
					id: 'lesson-symptoms-aches',
					unitId,
					categoryId: healthId,
					order: 1,
					title: 'Symptoms',
					subtitle: 'Say what hurts',
					description: 'Talk about common ailments and aches.',
					grammarNote:
						'Use "Masakit ang..." for "My ... hurts" or "The ... hurts."',
					color: 'from-cyan-400 to-sky-500',
					introCards: [
						{
							id: 'intro-symptom-1',
							kind: 'phrase',
							tagalog: 'Masakit ang ulo ko',
							meaning: 'My head hurts',
							audioText: 'Masakit ang ulo ko',
							example: 'A common symptom sentence.',
							emoji: 'Headache',
						},
						{
							id: 'intro-symptom-2',
							kind: 'word',
							tagalog: 'Lagnat',
							meaning: 'Fever',
							audioText: 'Lagnat',
							example: 'A common ailment word.',
							emoji: 'Fever',
						},
						{
							id: 'intro-symptom-3',
							kind: 'word',
							tagalog: 'Ubo',
							meaning: 'Cough',
							audioText: 'Ubo',
							example: 'Useful at a clinic or pharmacy.',
							emoji: 'Cough',
						},
					],
					matchPairs: [
						{ left: 'My head hurts', right: 'Masakit ang ulo ko' },
						{ left: 'fever', right: 'Lagnat' },
						{ left: 'cough', right: 'Ubo' },
					],
					buildPrompt: 'Build "My head hurts."',
					buildOptions: ['Masakit', 'ang', 'ulo', 'ko', 'ubo'],
					correctSequence: ['Masakit', 'ang', 'ulo', 'ko'],
					blankPrompt: 'Complete the symptom.',
					sentenceTemplate: 'May ___ ako.',
					acceptableAnswers: ['ubo', 'Ubo'],
					placeholder: 'Symptom',
					listeningPrompt: 'What symptom do you hear?',
					audioText: 'May lagnat ako',
					listeningOptions: [
						'I have a fever',
						'I have a cough',
						'My foot hurts',
					],
					correctAnswer: 'I have a fever',
					speakingPrompt: 'Say "I have a cough."',
					expectedTranscript: 'May ubo ako.',
					referenceTranslation: 'I have a cough.',
				}),
				createGeneratedLesson({
					id: 'lesson-simple-remedies',
					unitId,
					categoryId: healthId,
					order: 2,
					title: 'Simple Remedies',
					subtitle: 'Ask what helps',
					description: 'Talk about basic remedies and gentle advice.',
					grammarNote:
						'Use "Kailangan ko ng..." for "I need..." when asking for medicine, water, or rest.',
					color: 'from-sky-400 to-indigo-500',
					introCards: [
						{
							id: 'intro-remedy-1',
							kind: 'word',
							tagalog: 'Gamot',
							meaning: 'Medicine',
							audioText: 'Gamot',
							example: 'A key health word.',
							emoji: 'Medicine',
						},
						{
							id: 'intro-remedy-2',
							kind: 'word',
							tagalog: 'Pahinga',
							meaning: 'Rest',
							audioText: 'Pahinga',
							example: 'A simple remedy word.',
							emoji: 'Rest',
						},
						{
							id: 'intro-remedy-3',
							kind: 'phrase',
							tagalog: 'Kailangan ko ng gamot',
							meaning: 'I need medicine',
							audioText: 'Kailangan ko ng gamot',
							example: 'A practical health request.',
							emoji: 'Need',
						},
					],
					matchPairs: [
						{ left: 'medicine', right: 'Gamot' },
						{ left: 'rest', right: 'Pahinga' },
						{ left: 'I need medicine', right: 'Kailangan ko ng gamot' },
					],
					buildPrompt: 'Build "I need medicine."',
					buildOptions: ['Kailangan', 'ko', 'ng', 'gamot', 'pahinga'],
					correctSequence: ['Kailangan', 'ko', 'ng', 'gamot'],
					blankPrompt: 'Complete the remedy sentence.',
					sentenceTemplate: 'Kailangan ko ng ___.',
					acceptableAnswers: ['pahinga', 'Pahinga'],
					placeholder: 'Remedy',
					listeningPrompt: 'What does the speaker need?',
					audioText: 'Kailangan ko ng gamot',
					listeningOptions: ['medicine', 'water', 'food'],
					correctAnswer: 'medicine',
					speakingPrompt: 'Say "I need rest."',
					expectedTranscript: 'Kailangan ko ng pahinga.',
					referenceTranslation: 'I need rest.',
					finalExercise: 'listen-repeat',
				}),
			],
		},
	],
}
