import type { Unit } from "@/lib/domain/models"

export const unit02: Unit = {
  id: "unit-02",
  order: 2,
  title: "Meet People",
  description: "Introduce yourself with names, pronouns, and basic identity sentences.",
  theme: "Island teal",
  bannerTitle: "Talk about yourself",
  bannerSubtitle: "Introduce yourself, ask names, and build simple identity sentences.",
  categories: [
    {
      id: "unit-02-intros",
      unitId: "unit-02",
      order: 1,
      title: "Intro Trail",
      subtitle: "Say who you are",
      description: "Get comfortable with names, pronouns, and first introductions.",
      themeColor: "from-cyan-400 to-sky-500",
      accentColor: "bg-cyan-400",
      icon: "chat",
      hasGuidebook: true,
      lessons: [
        {
          id: "lesson-intros",
          unitId: "unit-02",
          categoryId: "unit-02-intros",
          order: 1,
          title: "Introductions",
          subtitle: "Say who you are",
          description: "Learn simple self-introductions and name patterns.",
          grammarNote:
            'A common way to say your name is "Ako si..." for casual contexts. "Ako ay..." can sound a bit more formal or explicit.',
          color: "from-teal-400 to-cyan-500",
          introCards: [
            {
              id: "intro-self-1",
              kind: "word",
              tagalog: "Ako",
              meaning: "I / me",
              audioText: "Ako",
              example: 'Use it when talking about yourself: "Ako si Mika."',
              emoji: "Me",
            },
            {
              id: "intro-self-2",
              kind: "word",
              tagalog: "Ikaw",
              meaning: "You",
              audioText: "Ikaw",
              example: "Use it when talking directly to another person.",
              emoji: "You",
            },
            {
              id: "intro-self-3",
              kind: "word",
              tagalog: "Pangalan",
              meaning: "Name",
              audioText: "Pangalan",
              example: 'As in "Ano pangalan mo?"',
              emoji: "Tag",
            },
          ],
          exercises: [
            {
              id: "intro-1",
              type: "tap-translation",
              prompt: 'Build "I am Mika."',
              instructions: "Tap the right answer.",
              xp: 6,
              options: [
                { id: "ako", label: "Ako", value: "Ako" },
                { id: "si", label: "si", value: "si" },
                { id: "mika", label: "Mika", value: "Mika" },
                { id: "ikaw", label: "ikaw", value: "ikaw" },
              ],
              correctSequence: ["Ako", "si", "Mika"],
            },
            {
              id: "intro-2",
              type: "word-matching",
              prompt: "Match the pronouns.",
              instructions: "Pair English and Tagalog.",
              xp: 5,
              pairs: [
                { left: "I", right: "Ako" },
                { left: "You", right: "Ikaw" },
                { left: "Name", right: "Pangalan" },
              ],
            },
            {
              id: "intro-3",
              type: "sentence-reorder",
              prompt: 'Reorder "What is your name?"',
              instructions: "Arrange the phrase.",
              xp: 6,
              tokens: ["pangalan", "Ano", "mo", "?"],
              correctSequence: ["Ano", "pangalan", "mo", "?"],
            },
            {
              id: "intro-4",
              type: "fill-in-the-blank",
              prompt: "Finish the sentence.",
              instructions: "Type the missing word.",
              xp: 6,
              sentenceTemplate: "Ako ___ Lila.",
              acceptableAnswers: ["si", "Si"],
              placeholder: "Missing word",
            },
            {
              id: "intro-5",
              type: "speaking-prompt",
              prompt: 'Say "My name is Paulo."',
              instructions: "Say it in Tagalog or type it.",
              xp: 8,
              expectedTranscript: "Ako si Paulo.",
              referenceTranslation: "My name is Paulo.",
            },
          ],
        },
        {
          id: "lesson-ask-names",
          unitId: "unit-02",
          categoryId: "unit-02-intros",
          order: 2,
          title: "Ask Names",
          subtitle: "Meet someone new",
          description: "Practice asking and answering names in quick first meetings.",
          grammarNote:
            'Questions often stay short in spoken Tagalog. "Ano pangalan mo?" is compact and useful right away.',
          color: "from-sky-400 to-blue-500",
          introCards: [
            {
              id: "intro-ask-1",
              kind: "phrase",
              tagalog: "Ano pangalan mo?",
              meaning: "What is your name?",
              audioText: "Ano pangalan mo?",
              example: "A direct and common first-meeting question.",
              emoji: "Question",
            },
            {
              id: "intro-ask-2",
              kind: "word",
              tagalog: "Mo",
              meaning: "your",
              audioText: "Mo",
              example: 'You hear it in "pangalan mo".',
              emoji: "Your",
            },
            {
              id: "intro-ask-3",
              kind: "phrase",
              tagalog: "Ako si Ana",
              meaning: "I am Ana",
              audioText: "Ako si Ana",
              example: "A clean simple reply after someone asks your name.",
              emoji: "Name",
            },
          ],
          exercises: [
            {
              id: "ask-name-1",
              type: "word-matching",
              prompt: "Match the intro phrases.",
              instructions: "Pair phrase and meaning.",
              xp: 5,
              pairs: [
                { left: "What is your name?", right: "Ano pangalan mo?" },
                { left: "I am Ana", right: "Ako si Ana" },
                { left: "your", right: "Mo" },
              ],
            },
            {
              id: "ask-name-2",
              type: "tap-translation",
              prompt: 'Build "What is your name?"',
              instructions: "Tap the phrase in order.",
              xp: 6,
              options: [
                { id: "ano", label: "Ano", value: "Ano" },
                { id: "pangalan", label: "pangalan", value: "pangalan" },
                { id: "mo", label: "mo?", value: "mo?" },
                { id: "ako", label: "ako", value: "ako" },
              ],
              correctSequence: ["Ano", "pangalan", "mo?"],
            },
            {
              id: "ask-name-3",
              type: "listening-mcq",
              prompt: "What question do you hear?",
              instructions: "Listen carefully.",
              xp: 6,
              audioText: "Ano pangalan mo?",
              options: [
                { id: "a", label: "What is your name?", value: "What is your name?" },
                { id: "b", label: "How are you?", value: "How are you?" },
                { id: "c", label: "Where are you from?", value: "Where are you from?" },
              ],
              correctAnswer: "What is your name?",
            },
            {
              id: "ask-name-4",
              type: "fill-in-the-blank",
              prompt: "Complete the answer.",
              instructions: "Type the missing word.",
              xp: 6,
              sentenceTemplate: "Ako ___ Ana.",
              acceptableAnswers: ["si", "Si"],
              placeholder: "Missing word",
            },
            {
              id: "ask-name-5",
              type: "listen-repeat",
              prompt: "Repeat the question.",
              instructions: "Listen and echo it back.",
              xp: 8,
              audioText: "Ano pangalan mo?",
              expectedTranscript: "Ano pangalan mo?",
            },
          ],
        },
        {
          id: "lesson-who-are-you",
          unitId: "unit-02",
          categoryId: "unit-02-intros",
          order: 3,
          title: "Who Are You",
          subtitle: "Handle basic identity lines",
          description: "Use simple identity phrases and short introductions naturally.",
          grammarNote:
            'You can mix names with simple identity labels like "estudyante" without needing long grammar explanations at this stage.',
          color: "from-indigo-400 to-sky-500",
          introCards: [
            {
              id: "intro-who-1",
              kind: "word",
              tagalog: "Estudyante",
              meaning: "Student",
              audioText: "Estudyante",
              example: '"Estudyante ako" means "I am a student."',
              emoji: "Book",
            },
            {
              id: "intro-who-2",
              kind: "word",
              tagalog: "Kaibigan",
              meaning: "Friend",
              audioText: "Kaibigan",
              example: "A useful people word in introductions.",
              emoji: "Friend",
            },
            {
              id: "intro-who-3",
              kind: "phrase",
              tagalog: "Estudyante ako",
              meaning: "I am a student",
              audioText: "Estudyante ako",
              example: "A compact identity sentence.",
              emoji: "School",
            },
          ],
          exercises: [
            {
              id: "who-1",
              type: "sentence-reorder",
              prompt: 'Reorder "I am a student."',
              instructions: "Put the sentence together.",
              xp: 6,
              tokens: ["ako", "Estudyante"],
              correctSequence: ["Estudyante", "ako"],
            },
            {
              id: "who-2",
              type: "word-matching",
              prompt: "Match the identity words.",
              instructions: "Pair each English word with Tagalog.",
              xp: 5,
              pairs: [
                { left: "Student", right: "Estudyante" },
                { left: "Friend", right: "Kaibigan" },
                { left: "I", right: "Ako" },
              ],
            },
            {
              id: "who-3",
              type: "dictation",
              prompt: "Write what you hear.",
              instructions: "Type the full phrase.",
              xp: 7,
              audioText: "Estudyante ako",
              acceptableAnswers: ["Estudyante ako", "estudyante ako"],
            },
            {
              id: "who-4",
              type: "tap-translation",
              prompt: 'Build "Friend".',
              instructions: "Tap the correct word.",
              xp: 5,
              options: [
                { id: "kaibigan", label: "Kaibigan", value: "Kaibigan" },
                { id: "pangalan", label: "Pangalan", value: "Pangalan" },
                { id: "ikaw", label: "Ikaw", value: "Ikaw" },
              ],
              correctSequence: ["Kaibigan"],
            },
            {
              id: "who-5",
              type: "speaking-prompt",
              prompt: 'Say "I am a student."',
              instructions: "Speak or type your answer.",
              xp: 8,
              expectedTranscript: "Estudyante ako.",
              referenceTranslation: "I am a student.",
            },
          ],
        },
      ],
    },
    {
      id: "unit-02-self-talk",
      unitId: "unit-02",
      order: 2,
      title: "Self Talk Loop",
      subtitle: "Talk about yourself",
      description: "Describe your mood and identity with compact, useful sentences.",
      themeColor: "from-sky-400 to-blue-500",
      accentColor: "bg-sky-400",
      icon: "star",
      hasRewardChest: true,
      lessons: [
        {
          id: "lesson-simple-sentences",
          unitId: "unit-02",
          categoryId: "unit-02-self-talk",
          order: 1,
          title: "Simple Sentences",
          subtitle: "Talk about yourself",
          description: "Use pronouns and simple describing sentences.",
          grammarNote:
            'Tagalog often keeps sentences compact. Context helps a lot, so short lines like "Masaya ako" feel natural and complete.',
          color: "from-cyan-400 to-sky-500",
          introCards: [
            {
              id: "intro-simple-1",
              kind: "word",
              tagalog: "Masaya",
              meaning: "Happy",
              audioText: "Masaya",
              example: '"Masaya ako" means "I am happy."',
              emoji: "Happy",
            },
            {
              id: "intro-simple-2",
              kind: "word",
              tagalog: "Pagod",
              meaning: "Tired",
              audioText: "Pagod",
              example: '"Pagod ako" means "I am tired."',
              emoji: "Tired",
            },
            {
              id: "intro-simple-3",
              kind: "word",
              tagalog: "Mabait",
              meaning: "Kind",
              audioText: "Mabait",
              example: '"Mabait ka" means "You are kind."',
              emoji: "Kind",
            },
          ],
          exercises: [
            {
              id: "simple-1",
              type: "listening-mcq",
              prompt: "What do you hear?",
              instructions: "Choose the best translation.",
              xp: 6,
              audioText: "Masaya ako",
              options: [
                { id: "a", label: "I am happy", value: "I am happy" },
                { id: "b", label: "I am tired", value: "I am tired" },
                { id: "c", label: "You are happy", value: "You are happy" },
              ],
              correctAnswer: "I am happy",
            },
            {
              id: "simple-2",
              type: "dictation",
              prompt: "Write the phrase you hear.",
              instructions: "Type the Tagalog sentence.",
              xp: 7,
              audioText: "Pagod ako",
              acceptableAnswers: ["Pagod ako", "pagod ako"],
              helperText: 'This means "I am tired."',
            },
            {
              id: "simple-3",
              type: "tap-translation",
              prompt: 'Build "You are kind."',
              instructions: "Tap the tiles in order.",
              xp: 6,
              options: [
                { id: "mabait", label: "Mabait", value: "Mabait" },
                { id: "ka", label: "ka", value: "ka" },
                { id: "ako", label: "ako", value: "ako" },
              ],
              correctSequence: ["Mabait", "ka"],
            },
            {
              id: "simple-4",
              type: "sentence-reorder",
              prompt: 'Reorder "Student ako."',
              instructions: "Put the sentence together.",
              xp: 6,
              tokens: ["ako", "Estudyante"],
              correctSequence: ["Estudyante", "ako"],
            },
            {
              id: "simple-5",
              type: "listen-repeat",
              prompt: "Repeat the sentence.",
              instructions: "Listen and echo it.",
              xp: 8,
              audioText: "Mabait ako",
              expectedTranscript: "Mabait ako",
            },
          ],
        },
        {
          id: "lesson-feelings",
          unitId: "unit-02",
          categoryId: "unit-02-self-talk",
          order: 2,
          title: "Feelings",
          subtitle: "Share how you feel",
          description: "Expand beyond happy and tired with a few more everyday feeling words.",
          grammarNote:
            'Many feeling words work the same way: adjective first, pronoun second, as in "Malungkot ako".',
          color: "from-blue-400 to-indigo-500",
          introCards: [
            {
              id: "intro-feel-1",
              kind: "word",
              tagalog: "Malungkot",
              meaning: "Sad",
              audioText: "Malungkot",
              example: '"Malungkot ako" means "I am sad."',
              emoji: "Sad",
            },
            {
              id: "intro-feel-2",
              kind: "word",
              tagalog: "Excited",
              meaning: "Excited",
              audioText: "Excited",
              example: "You may also hear familiar borrowed words in Tagalog speech.",
              emoji: "Excited",
            },
            {
              id: "intro-feel-3",
              kind: "phrase",
              tagalog: "Masaya ako",
              meaning: "I am happy",
              audioText: "Masaya ako",
              example: "A quick useful feeling sentence.",
              emoji: "Bright",
            },
          ],
          exercises: [
            {
              id: "feel-1",
              type: "word-matching",
              prompt: "Match the feeling words.",
              instructions: "Pair English and Tagalog.",
              xp: 5,
              pairs: [
                { left: "Sad", right: "Malungkot" },
                { left: "Happy", right: "Masaya" },
                { left: "Tired", right: "Pagod" },
              ],
            },
            {
              id: "feel-2",
              type: "tap-translation",
              prompt: 'Build "I am sad."',
              instructions: "Tap the phrase in order.",
              xp: 6,
              options: [
                { id: "malungkot", label: "Malungkot", value: "Malungkot" },
                { id: "ako", label: "ako", value: "ako" },
                { id: "ikaw", label: "ikaw", value: "ikaw" },
              ],
              correctSequence: ["Malungkot", "ako"],
            },
            {
              id: "feel-3",
              type: "listening-mcq",
              prompt: "What feeling do you hear?",
              instructions: "Choose the best meaning.",
              xp: 6,
              audioText: "Pagod ako",
              options: [
                { id: "a", label: "I am tired", value: "I am tired" },
                { id: "b", label: "I am kind", value: "I am kind" },
                { id: "c", label: "I am excited", value: "I am excited" },
              ],
              correctAnswer: "I am tired",
            },
            {
              id: "feel-4",
              type: "fill-in-the-blank",
              prompt: "Complete the sentence.",
              instructions: "Type the missing feeling word.",
              xp: 6,
              sentenceTemplate: "___ ako.",
              acceptableAnswers: ["Masaya", "masaya"],
              placeholder: "Missing word",
            },
            {
              id: "feel-5",
              type: "speaking-prompt",
              prompt: 'Say "I am happy."',
              instructions: "Speak or type the phrase.",
              xp: 8,
              expectedTranscript: "Masaya ako.",
              referenceTranslation: "I am happy.",
            },
          ],
        },
        {
          id: "lesson-identity-lines",
          unitId: "unit-02",
          categoryId: "unit-02-self-talk",
          order: 3,
          title: "Identity Lines",
          subtitle: "Describe yourself simply",
          description: "Combine traits and identity words in short useful self-descriptions.",
          grammarNote:
            "You can reuse the same compact sentence pattern for many identity and personality descriptions.",
          color: "from-violet-400 to-sky-500",
          introCards: [
            {
              id: "intro-identity-1",
              kind: "word",
              tagalog: "Tahimik",
              meaning: "Quiet",
              audioText: "Tahimik",
              example: '"Tahimik ako" means "I am quiet."',
              emoji: "Quiet",
            },
            {
              id: "intro-identity-2",
              kind: "word",
              tagalog: "Masipag",
              meaning: "Hardworking",
              audioText: "Masipag",
              example: '"Masipag siya" means "He or she is hardworking."',
              emoji: "Work",
            },
            {
              id: "intro-identity-3",
              kind: "phrase",
              tagalog: "Mabait ako",
              meaning: "I am kind",
              audioText: "Mabait ako",
              example: "A simple positive self-description.",
              emoji: "Heart",
            },
          ],
          exercises: [
            {
              id: "identity-1",
              type: "sentence-reorder",
              prompt: 'Reorder "I am kind."',
              instructions: "Put the words together.",
              xp: 6,
              tokens: ["ako", "Mabait"],
              correctSequence: ["Mabait", "ako"],
            },
            {
              id: "identity-2",
              type: "word-matching",
              prompt: "Match the trait words.",
              instructions: "Pair each trait and meaning.",
              xp: 5,
              pairs: [
                { left: "Quiet", right: "Tahimik" },
                { left: "Hardworking", right: "Masipag" },
                { left: "Kind", right: "Mabait" },
              ],
            },
            {
              id: "identity-3",
              type: "dictation",
              prompt: "Write the phrase you hear.",
              instructions: "Type the full sentence.",
              xp: 7,
              audioText: "Mabait ako",
              acceptableAnswers: ["Mabait ako", "mabait ako"],
            },
            {
              id: "identity-4",
              type: "tap-translation",
              prompt: 'Build "Quiet".',
              instructions: "Tap the right word.",
              xp: 5,
              options: [
                { id: "tahimik", label: "Tahimik", value: "Tahimik" },
                { id: "masipag", label: "Masipag", value: "Masipag" },
                { id: "masaya", label: "Masaya", value: "Masaya" },
              ],
              correctSequence: ["Tahimik"],
            },
            {
              id: "identity-5",
              type: "listen-repeat",
              prompt: "Repeat the trait sentence.",
              instructions: "Listen and say it back.",
              xp: 8,
              audioText: "Tahimik ako",
              expectedTranscript: "Tahimik ako",
            },
          ],
        },
      ],
    },
  ],
}
