import type { Unit } from '@/lib/domain/models'

import { createGeneratedLesson } from '@/content/units/unit-helpers'

const unitId = 'unit-08'
const travelId = 'unit-08-travel-plans'
const reactionsId = 'unit-08-reactions'
const storiesId = 'unit-08-storytelling'

export const unit08: Unit = {
	id: unitId,
	order: 8,
	title: 'Travel and Stories',
	description:
		'Trips, tickets, reactions, feelings, events, and simple stories.',
	theme: 'Sky journey',
	bannerTitle: 'Tell what happened',
	bannerSubtitle:
		'Talk about trips, future plans, reactions, and short events.',
	categories: [
		{
			id: travelId,
			unitId,
			order: 1,
			title: 'Travel Plans',
			subtitle: 'Past and future trips',
			description: 'Talk about previous holidays and book a plane ticket.',
			themeColor: 'from-sky-400 to-blue-500',
			accentColor: 'bg-sky-400',
			icon: 'guidebook',
			hasGuidebook: true,
			lessons: [
				createGeneratedLesson({
					id: 'lesson-previous-holidays',
					unitId,
					categoryId: travelId,
					order: 1,
					title: 'Previous Holidays',
					subtitle: 'Say where you went',
					description: 'Use simple past-trip phrases.',
					grammarNote:
						'Use "Pumunta ako sa..." for "I went to..." when talking about a completed trip.',
					color: 'from-sky-400 to-cyan-500',
					introCards: [
						{
							id: 'intro-holiday-1',
							kind: 'phrase',
							tagalog: 'Pumunta ako sa Baguio',
							meaning: 'I went to Baguio',
							audioText: 'Pumunta ako sa Baguio',
							example: 'A useful past travel sentence.',
							emoji: 'Trip',
						},
						{
							id: 'intro-holiday-2',
							kind: 'word',
							tagalog: 'Bakasyon',
							meaning: 'Vacation / holiday',
							audioText: 'Bakasyon',
							example: 'A common travel word.',
							emoji: 'Vacation',
						},
						{
							id: 'intro-holiday-3',
							kind: 'word',
							tagalog: 'Noon',
							meaning: 'Before / in the past',
							audioText: 'Noon',
							example: 'Use it to point back in time.',
							emoji: 'Past',
						},
					],
					matchPairs: [
						{ left: 'I went to Baguio', right: 'Pumunta ako sa Baguio' },
						{ left: 'vacation', right: 'Bakasyon' },
						{ left: 'before / in the past', right: 'Noon' },
					],
					buildPrompt: 'Build "I went to Baguio."',
					buildOptions: ['Pumunta', 'ako', 'sa', 'Baguio', 'bukas'],
					correctSequence: ['Pumunta', 'ako', 'sa', 'Baguio'],
					blankPrompt: 'Complete the past trip.',
					sentenceTemplate: 'Pumunta ako sa ___ noon.',
					acceptableAnswers: ['Baguio', 'baguio'],
					placeholder: 'Place',
					listeningPrompt: 'Where did the speaker go?',
					audioText: 'Pumunta ako sa Baguio',
					listeningOptions: ['Baguio', 'Cebu', 'Manila'],
					correctAnswer: 'Baguio',
					speakingPrompt: 'Say "I went to Baguio."',
					expectedTranscript: 'Pumunta ako sa Baguio.',
					referenceTranslation: 'I went to Baguio.',
				}),
				createGeneratedLesson({
					id: 'lesson-plane-ticket',
					unitId,
					categoryId: travelId,
					order: 2,
					title: 'Plane Ticket',
					subtitle: 'Book a flight',
					description: 'Ask for a plane ticket and talk about future travel.',
					grammarNote:
						'Use "Gusto kong..." before an action to say "I want to..."',
					color: 'from-blue-400 to-indigo-500',
					introCards: [
						{
							id: 'intro-ticket-1',
							kind: 'phrase',
							tagalog: 'Gusto kong bumili ng tiket',
							meaning: 'I want to buy a ticket',
							audioText: 'Gusto kong bumili ng tiket',
							example: 'A useful booking phrase.',
							emoji: 'Ticket',
						},
						{
							id: 'intro-ticket-2',
							kind: 'word',
							tagalog: 'Eroplano',
							meaning: 'Airplane',
							audioText: 'Eroplano',
							example: 'A common travel word.',
							emoji: 'Plane',
						},
						{
							id: 'intro-ticket-3',
							kind: 'word',
							tagalog: 'Tiket',
							meaning: 'Ticket',
							audioText: 'Tiket',
							example: 'A useful borrowed word.',
							emoji: 'Ticket',
						},
					],
					matchPairs: [
						{
							left: 'I want to buy a ticket',
							right: 'Gusto kong bumili ng tiket',
						},
						{ left: 'airplane', right: 'Eroplano' },
						{ left: 'ticket', right: 'Tiket' },
					],
					buildPrompt: 'Build "I want to buy a ticket."',
					buildOptions: ['Gusto', 'kong', 'bumili', 'ng', 'tiket', 'eroplano'],
					correctSequence: ['Gusto', 'kong', 'bumili', 'ng', 'tiket'],
					blankPrompt: 'Complete the booking phrase.',
					sentenceTemplate: 'Gusto kong bumili ng ___.',
					acceptableAnswers: ['tiket', 'Tiket'],
					placeholder: 'Item',
					listeningPrompt: 'What does the speaker want?',
					audioText: 'Gusto kong bumili ng tiket',
					listeningOptions: ['to buy a ticket', 'to go home', 'to eat rice'],
					correctAnswer: 'to buy a ticket',
					speakingPrompt: 'Say "I want to buy a ticket."',
					expectedTranscript: 'Gusto kong bumili ng tiket.',
					referenceTranslation: 'I want to buy a ticket.',
					finalExercise: 'listen-repeat',
				}),
			],
		},
		{
			id: reactionsId,
			unitId,
			order: 2,
			title: 'Feelings and Reactions',
			subtitle: 'React to events',
			description:
				'Express reactions and feelings about past and future activities.',
			themeColor: 'from-rose-400 to-pink-500',
			accentColor: 'bg-rose-400',
			icon: 'star',
			lessons: [
				createGeneratedLesson({
					id: 'lesson-reactions-feelings',
					unitId,
					categoryId: reactionsId,
					order: 1,
					title: 'Reactions',
					subtitle: 'Say how it felt',
					description: 'React to events with short expressive phrases.',
					grammarNote:
						'Reaction words like "Masaya" and "Nakakatuwa" can stand alone or describe an event.',
					color: 'from-rose-400 to-fuchsia-500',
					introCards: [
						{
							id: 'intro-react-1',
							kind: 'word',
							tagalog: 'Nakakatuwa',
							meaning: 'Delightful / fun',
							audioText: 'Nakakatuwa',
							example: 'A warm reaction word.',
							emoji: 'Delight',
						},
						{
							id: 'intro-react-2',
							kind: 'word',
							tagalog: 'Nakakalungkot',
							meaning: 'Sad',
							audioText: 'Nakakalungkot',
							example: 'Use it for sad news or scenes.',
							emoji: 'Sad',
						},
						{
							id: 'intro-react-3',
							kind: 'phrase',
							tagalog: 'Masaya ang bakasyon',
							meaning: 'The vacation is fun',
							audioText: 'Masaya ang bakasyon',
							example: 'A simple reaction to a trip.',
							emoji: 'Fun',
						},
					],
					matchPairs: [
						{ left: 'delightful / fun', right: 'Nakakatuwa' },
						{ left: 'sad', right: 'Nakakalungkot' },
						{ left: 'The vacation is fun', right: 'Masaya ang bakasyon' },
					],
					buildPrompt: 'Build "The vacation is fun."',
					buildOptions: ['Masaya', 'ang', 'bakasyon', 'malungkot'],
					correctSequence: ['Masaya', 'ang', 'bakasyon'],
					blankPrompt: 'Complete the reaction.',
					sentenceTemplate: '___ ang kuwento.',
					acceptableAnswers: ['Nakakalungkot', 'nakakalungkot'],
					placeholder: 'Reaction',
					listeningPrompt: 'What reaction do you hear?',
					audioText: 'Nakakatuwa',
					listeningOptions: ['delightful / fun', 'sad', 'tiring'],
					correctAnswer: 'delightful / fun',
					speakingPrompt: 'Say "The vacation is fun."',
					expectedTranscript: 'Masaya ang bakasyon.',
					referenceTranslation: 'The vacation is fun.',
				}),
				createGeneratedLesson({
					id: 'lesson-past-future-activities',
					unitId,
					categoryId: reactionsId,
					order: 2,
					title: 'Past and Future',
					subtitle: 'Then and tomorrow',
					description:
						'Talk about past and future activities with simple time words.',
					grammarNote:
						'Use "kahapon" for yesterday and "bukas" for tomorrow to anchor simple event sentences.',
					color: 'from-pink-400 to-orange-500',
					introCards: [
						{
							id: 'intro-past-future-1',
							kind: 'word',
							tagalog: 'Kahapon',
							meaning: 'Yesterday',
							audioText: 'Kahapon',
							example: 'Use it for past events.',
							emoji: 'Yesterday',
						},
						{
							id: 'intro-past-future-2',
							kind: 'phrase',
							tagalog: 'Bukas ako pupunta',
							meaning: 'I will go tomorrow',
							audioText: 'Bukas ako pupunta',
							example: 'A simple future activity sentence.',
							emoji: 'Tomorrow',
						},
						{
							id: 'intro-past-future-3',
							kind: 'phrase',
							tagalog: 'Kumain ako kahapon',
							meaning: 'I ate yesterday',
							audioText: 'Kumain ako kahapon',
							example: 'A simple past activity sentence.',
							emoji: 'Ate',
						},
					],
					matchPairs: [
						{ left: 'yesterday', right: 'Kahapon' },
						{ left: 'I will go tomorrow', right: 'Bukas ako pupunta' },
						{ left: 'I ate yesterday', right: 'Kumain ako kahapon' },
					],
					buildPrompt: 'Build "I ate yesterday."',
					buildOptions: ['Kumain', 'ako', 'kahapon', 'bukas'],
					correctSequence: ['Kumain', 'ako', 'kahapon'],
					blankPrompt: 'Complete the future activity.',
					sentenceTemplate: '___ ako pupunta.',
					acceptableAnswers: ['Bukas', 'bukas'],
					placeholder: 'Time word',
					listeningPrompt: 'When did the speaker eat?',
					audioText: 'Kumain ako kahapon',
					listeningOptions: ['yesterday', 'tomorrow', 'today'],
					correctAnswer: 'yesterday',
					speakingPrompt: 'Say "I will go tomorrow."',
					expectedTranscript: 'Bukas ako pupunta.',
					referenceTranslation: 'I will go tomorrow.',
					finalExercise: 'dictation',
				}),
			],
		},
		{
			id: storiesId,
			unitId,
			order: 3,
			title: 'Storytelling',
			subtitle: 'Narrate events',
			description: 'Narrate events and tell simple stories in sequence.',
			themeColor: 'from-amber-400 to-yellow-500',
			accentColor: 'bg-amber-400',
			icon: 'music',
			hasRewardChest: true,
			lessons: [
				createGeneratedLesson({
					id: 'lesson-event-sequence',
					unitId,
					categoryId: storiesId,
					order: 1,
					title: 'Event Sequence',
					subtitle: 'First, then, after',
					description: 'Use sequence words to narrate small events.',
					grammarNote:
						'Use "Una" for first and "Pagkatapos" for after/then when linking events.',
					color: 'from-amber-400 to-orange-500',
					introCards: [
						{
							id: 'intro-sequence-1',
							kind: 'word',
							tagalog: 'Una',
							meaning: 'First',
							audioText: 'Una',
							example: 'Start a short sequence.',
							emoji: 'First',
						},
						{
							id: 'intro-sequence-2',
							kind: 'word',
							tagalog: 'Pagkatapos',
							meaning: 'After / then',
							audioText: 'Pagkatapos',
							example: 'Move to the next event.',
							emoji: 'Then',
						},
						{
							id: 'intro-sequence-3',
							kind: 'phrase',
							tagalog: 'Una, kumain ako',
							meaning: 'First, I ate',
							audioText: 'Una, kumain ako',
							example: 'A simple story opening.',
							emoji: 'Story',
						},
					],
					matchPairs: [
						{ left: 'first', right: 'Una' },
						{ left: 'after / then', right: 'Pagkatapos' },
						{ left: 'First, I ate', right: 'Una, kumain ako' },
					],
					buildPrompt: 'Build "First, I ate."',
					buildOptions: ['Una', 'kumain', 'ako', 'pagkatapos'],
					correctSequence: ['Una', 'kumain', 'ako'],
					blankPrompt: 'Complete the sequence word.',
					sentenceTemplate: '___, natulog ako.',
					acceptableAnswers: ['Pagkatapos', 'pagkatapos'],
					placeholder: 'Then',
					listeningPrompt: 'What sequence word do you hear?',
					audioText: 'Pagkatapos',
					listeningOptions: ['after / then', 'first', 'yesterday'],
					correctAnswer: 'after / then',
					speakingPrompt: 'Say "First, I ate."',
					expectedTranscript: 'Una, kumain ako.',
					referenceTranslation: 'First, I ate.',
				}),
				createGeneratedLesson({
					id: 'lesson-short-story',
					unitId,
					categoryId: storiesId,
					order: 2,
					title: 'Short Story',
					subtitle: 'Retell a simple event',
					description: 'Summarize a tiny story using familiar verbs.',
					grammarNote:
						'A simple story can be only two or three short sentences if the order is clear.',
					color: 'from-yellow-400 to-lime-500',
					introCards: [
						{
							id: 'intro-short-story-1',
							kind: 'phrase',
							tagalog: 'May bata sa bahay',
							meaning: 'There is a child at home',
							audioText: 'May bata sa bahay',
							example: 'A simple story setup.',
							emoji: 'Child',
						},
						{
							id: 'intro-short-story-2',
							kind: 'phrase',
							tagalog: 'Naglaro siya',
							meaning: 'He or she played',
							audioText: 'Naglaro siya',
							example: 'A simple event sentence.',
							emoji: 'Played',
						},
						{
							id: 'intro-short-story-3',
							kind: 'word',
							tagalog: 'Kuwento',
							meaning: 'Story',
							audioText: 'Kuwento',
							example: 'Useful when talking about stories.',
							emoji: 'Story',
						},
					],
					matchPairs: [
						{ left: 'story', right: 'Kuwento' },
						{ left: 'He or she played', right: 'Naglaro siya' },
						{ left: 'There is a child at home', right: 'May bata sa bahay' },
					],
					buildPrompt: 'Build "He or she played."',
					buildOptions: ['Naglaro', 'siya', 'bata', 'bahay'],
					correctSequence: ['Naglaro', 'siya'],
					blankPrompt: 'Complete the story setup.',
					sentenceTemplate: 'May bata sa ___.',
					acceptableAnswers: ['bahay', 'Bahay'],
					placeholder: 'Place',
					listeningPrompt: 'What happened?',
					audioText: 'Naglaro siya',
					listeningOptions: [
						'He or she played',
						'He or she slept',
						'He or she ate',
					],
					correctAnswer: 'He or she played',
					speakingPrompt: 'Say "There is a child at home."',
					expectedTranscript: 'May bata sa bahay.',
					referenceTranslation: 'There is a child at home.',
					finalExercise: 'listen-repeat',
				}),
			],
		},
	],
}
