import type { Unit } from '@/lib/domain/models'

import { createGeneratedLesson } from '@/content/units/unit-helpers'

const unitId = 'unit-09'
const filmsId = 'unit-09-films'
const musicId = 'unit-09-abilities-music'
const legendsId = 'unit-09-legends'

export const unit09: Unit = {
	id: unitId,
	order: 9,
	title: 'Culture and Media',
	description:
		'Films, opinions, abilities, music, and popular Filipino legends.',
	theme: 'Festival night',
	bannerTitle: 'Enjoy culture and stories',
	bannerSubtitle:
		'Discuss films, abilities, songs, and familiar Filipino legends.',
	categories: [
		{
			id: filmsId,
			unitId,
			order: 1,
			title: 'Films',
			subtitle: 'Summaries and views',
			description:
				'Summarize a film, understand a review, and express your view.',
			themeColor: 'from-red-400 to-rose-500',
			accentColor: 'bg-red-400',
			icon: 'star',
			hasGuidebook: true,
			lessons: [
				createGeneratedLesson({
					id: 'lesson-film-summary',
					unitId,
					categoryId: filmsId,
					order: 1,
					title: 'Film Summary',
					subtitle: 'Say what it is about',
					description: 'Use simple film vocabulary and summary phrases.',
					grammarNote:
						'Use "Tungkol sa..." for "about..." when summarizing a film or story.',
					color: 'from-red-400 to-pink-500',
					introCards: [
						{
							id: 'intro-film-1',
							kind: 'word',
							tagalog: 'Pelikula',
							meaning: 'Film / movie',
							audioText: 'Pelikula',
							example: 'A core media word.',
							emoji: 'Film',
						},
						{
							id: 'intro-film-2',
							kind: 'phrase',
							tagalog: 'Tungkol sa pamilya',
							meaning: 'About family',
							audioText: 'Tungkol sa pamilya',
							example: 'Use it in a short summary.',
							emoji: 'Family',
						},
						{
							id: 'intro-film-3',
							kind: 'word',
							tagalog: 'Tauhan',
							meaning: 'Character',
							audioText: 'Tauhan',
							example: 'Useful when discussing stories and films.',
							emoji: 'Character',
						},
					],
					matchPairs: [
						{ left: 'film / movie', right: 'Pelikula' },
						{ left: 'about family', right: 'Tungkol sa pamilya' },
						{ left: 'character', right: 'Tauhan' },
					],
					buildPrompt: 'Build "The film is about family."',
					buildOptions: ['Ang', 'pelikula', 'ay', 'tungkol', 'sa', 'pamilya'],
					correctSequence: [
						'Ang',
						'pelikula',
						'ay',
						'tungkol',
						'sa',
						'pamilya',
					],
					blankPrompt: 'Complete the film summary.',
					sentenceTemplate: 'Tungkol sa ___ ang pelikula.',
					acceptableAnswers: ['pamilya', 'Pamilya'],
					placeholder: 'Topic',
					listeningPrompt: 'What is the film about?',
					audioText: 'Tungkol sa pamilya',
					listeningOptions: ['family', 'travel', 'food'],
					correctAnswer: 'family',
					speakingPrompt: 'Say "The film is about family."',
					expectedTranscript: 'Ang pelikula ay tungkol sa pamilya.',
					referenceTranslation: 'The film is about family.',
				}),
				createGeneratedLesson({
					id: 'lesson-film-review',
					unitId,
					categoryId: filmsId,
					order: 2,
					title: 'Film Review',
					subtitle: 'Give your view',
					description: 'Understand short film reviews and express an opinion.',
					grammarNote:
						'Use "Sa tingin ko..." for "I think..." before sharing an opinion.',
					color: 'from-rose-400 to-fuchsia-500',
					introCards: [
						{
							id: 'intro-review-1',
							kind: 'phrase',
							tagalog: 'Sa tingin ko',
							meaning: 'I think',
							audioText: 'Sa tingin ko',
							example: 'A polite opinion opener.',
							emoji: 'Think',
						},
						{
							id: 'intro-review-2',
							kind: 'phrase',
							tagalog: 'Maganda ang pelikula',
							meaning: 'The film is good',
							audioText: 'Maganda ang pelikula',
							example: 'A simple positive review.',
							emoji: 'Good',
						},
						{
							id: 'intro-review-3',
							kind: 'word',
							tagalog: 'Nakakainip',
							meaning: 'Boring',
							audioText: 'Nakakainip',
							example: 'A useful review word.',
							emoji: 'Boring',
						},
					],
					matchPairs: [
						{ left: 'I think', right: 'Sa tingin ko' },
						{ left: 'The film is good', right: 'Maganda ang pelikula' },
						{ left: 'boring', right: 'Nakakainip' },
					],
					buildPrompt: 'Build "I think the film is good."',
					buildOptions: ['Sa', 'tingin', 'ko', 'maganda', 'ang', 'pelikula'],
					correctSequence: ['Sa', 'tingin', 'ko', 'maganda', 'ang', 'pelikula'],
					blankPrompt: 'Complete the review.',
					sentenceTemplate: 'Sa tingin ko ___ ang pelikula.',
					acceptableAnswers: ['maganda', 'Maganda'],
					placeholder: 'Opinion',
					listeningPrompt: 'What review word do you hear?',
					audioText: 'Nakakainip',
					listeningOptions: ['boring', 'good', 'funny'],
					correctAnswer: 'boring',
					speakingPrompt: 'Say "The film is good."',
					expectedTranscript: 'Maganda ang pelikula.',
					referenceTranslation: 'The film is good.',
					finalExercise: 'listen-repeat',
				}),
			],
		},
		{
			id: musicId,
			unitId,
			order: 2,
			title: 'Abilities and Music',
			subtitle: 'Can, cannot, and song lines',
			description:
				'Say what you can do and practice a simple Filipino song phrase.',
			themeColor: 'from-purple-400 to-indigo-500',
			accentColor: 'bg-purple-400',
			icon: 'music',
			lessons: [
				createGeneratedLesson({
					id: 'lesson-can-cannot',
					unitId,
					categoryId: musicId,
					order: 1,
					title: 'Can and Cannot',
					subtitle: 'Talk about ability',
					description: 'Say what you can and cannot do.',
					grammarNote:
						'Use "Kaya kong..." for "I can..." and "Hindi ko kaya..." for "I cannot..."',
					color: 'from-purple-400 to-violet-500',
					introCards: [
						{
							id: 'intro-can-1',
							kind: 'phrase',
							tagalog: 'Kaya kong kumanta',
							meaning: 'I can sing',
							audioText: 'Kaya kong kumanta',
							example: 'A simple ability sentence.',
							emoji: 'Sing',
						},
						{
							id: 'intro-can-2',
							kind: 'phrase',
							tagalog: 'Hindi ko kaya',
							meaning: 'I cannot / I cannot do it',
							audioText: 'Hindi ko kaya',
							example: 'A useful limit phrase.',
							emoji: 'Cannot',
						},
						{
							id: 'intro-can-3',
							kind: 'word',
							tagalog: 'Sumayaw',
							meaning: 'To dance',
							audioText: 'Sumayaw',
							example: 'Use it after ability phrases.',
							emoji: 'Dance',
						},
					],
					matchPairs: [
						{ left: 'I can sing', right: 'Kaya kong kumanta' },
						{ left: 'I cannot', right: 'Hindi ko kaya' },
						{ left: 'to dance', right: 'Sumayaw' },
					],
					buildPrompt: 'Build "I can sing."',
					buildOptions: ['Kaya', 'kong', 'kumanta', 'sumayaw'],
					correctSequence: ['Kaya', 'kong', 'kumanta'],
					blankPrompt: 'Complete the ability phrase.',
					sentenceTemplate: 'Kaya kong ___.',
					acceptableAnswers: ['sumayaw', 'Sumayaw'],
					placeholder: 'Action',
					listeningPrompt: 'What can the speaker do?',
					audioText: 'Kaya kong kumanta',
					listeningOptions: ['sing', 'dance', 'cook'],
					correctAnswer: 'sing',
					speakingPrompt: 'Say "I cannot do it."',
					expectedTranscript: 'Hindi ko kaya.',
					referenceTranslation: 'I cannot do it.',
				}),
				createGeneratedLesson({
					id: 'lesson-song-expression',
					unitId,
					categoryId: musicId,
					order: 2,
					title: 'Song Expression',
					subtitle: 'Practice a song-like line',
					description: 'Use simple musical phrases and expressive language.',
					grammarNote:
						'Song lines often use compact, emotional language. Practice them as phrases before analyzing every word.',
					color: 'from-indigo-400 to-blue-500',
					introCards: [
						{
							id: 'intro-song-1',
							kind: 'word',
							tagalog: 'Awit',
							meaning: 'Song',
							audioText: 'Awit',
							example: 'A common word for song.',
							emoji: 'Song',
						},
						{
							id: 'intro-song-2',
							kind: 'word',
							tagalog: 'Kumanta',
							meaning: 'To sing',
							audioText: 'Kumanta',
							example: 'Use it for singing ability or activity.',
							emoji: 'Sing',
						},
						{
							id: 'intro-song-3',
							kind: 'phrase',
							tagalog: 'Maganda ang awit',
							meaning: 'The song is beautiful',
							audioText: 'Maganda ang awit',
							example: 'A simple reaction to a Filipino song.',
							emoji: 'Beautiful',
						},
					],
					matchPairs: [
						{ left: 'song', right: 'Awit' },
						{ left: 'to sing', right: 'Kumanta' },
						{ left: 'The song is beautiful', right: 'Maganda ang awit' },
					],
					buildPrompt: 'Build "The song is beautiful."',
					buildOptions: ['Maganda', 'ang', 'awit', 'pelikula'],
					correctSequence: ['Maganda', 'ang', 'awit'],
					blankPrompt: 'Complete the music sentence.',
					sentenceTemplate: 'Kaya kong ___.',
					acceptableAnswers: ['kumanta', 'Kumanta'],
					placeholder: 'Music action',
					listeningPrompt: 'What is beautiful?',
					audioText: 'Maganda ang awit',
					listeningOptions: ['the song', 'the film', 'the story'],
					correctAnswer: 'the song',
					speakingPrompt: 'Say "The song is beautiful."',
					expectedTranscript: 'Maganda ang awit.',
					referenceTranslation: 'The song is beautiful.',
					finalExercise: 'dictation',
				}),
			],
		},
		{
			id: legendsId,
			unitId,
			order: 3,
			title: 'Legends',
			subtitle: 'Popular Filipino stories',
			description:
				'Familiarize yourself with popular Filipino legends through simple lines.',
			themeColor: 'from-amber-400 to-orange-500',
			accentColor: 'bg-amber-400',
			icon: 'trophy',
			hasRewardChest: true,
			lessons: [
				createGeneratedLesson({
					id: 'lesson-legend-characters',
					unitId,
					categoryId: legendsId,
					order: 1,
					title: 'Legend Characters',
					subtitle: 'Meet story figures',
					description: 'Recognize simple words used in legends and folktales.',
					grammarNote:
						'Legends often start with "May..." to introduce a person, place, or problem.',
					color: 'from-amber-400 to-yellow-500',
					introCards: [
						{
							id: 'intro-legend-1',
							kind: 'word',
							tagalog: 'Alamat',
							meaning: 'Legend',
							audioText: 'Alamat',
							example: 'A key culture and story word.',
							emoji: 'Legend',
						},
						{
							id: 'intro-legend-2',
							kind: 'word',
							tagalog: 'Bayani',
							meaning: 'Hero',
							audioText: 'Bayani',
							example: 'A common story character word.',
							emoji: 'Hero',
						},
						{
							id: 'intro-legend-3',
							kind: 'word',
							tagalog: 'Bundok',
							meaning: 'Mountain',
							audioText: 'Bundok',
							example: 'Useful in many folktale settings.',
							emoji: 'Mountain',
						},
					],
					matchPairs: [
						{ left: 'legend', right: 'Alamat' },
						{ left: 'hero', right: 'Bayani' },
						{ left: 'mountain', right: 'Bundok' },
					],
					buildPrompt: 'Build "There is a hero."',
					buildOptions: ['May', 'bayani', 'alamat', 'bundok'],
					correctSequence: ['May', 'bayani'],
					blankPrompt: 'Complete the legend phrase.',
					sentenceTemplate: 'May ___ sa alamat.',
					acceptableAnswers: ['bayani', 'Bayani'],
					placeholder: 'Character',
					listeningPrompt: 'Which legend word do you hear?',
					audioText: 'Alamat',
					listeningOptions: ['legend', 'hero', 'mountain'],
					correctAnswer: 'legend',
					speakingPrompt: 'Say "There is a hero."',
					expectedTranscript: 'May bayani.',
					referenceTranslation: 'There is a hero.',
				}),
				createGeneratedLesson({
					id: 'lesson-simple-legend',
					unitId,
					categoryId: legendsId,
					order: 2,
					title: 'Simple Legend',
					subtitle: 'Understand a short line',
					description: 'Read and retell very simple legend-style sentences.',
					grammarNote:
						'For early reading practice, focus on who is in the story and where the story happens.',
					color: 'from-orange-400 to-red-500',
					introCards: [
						{
							id: 'intro-simple-legend-1',
							kind: 'phrase',
							tagalog: 'May alamat tungkol sa bundok',
							meaning: 'There is a legend about a mountain',
							audioText: 'May alamat tungkol sa bundok',
							example: 'A simple legend summary.',
							emoji: 'Mountain',
						},
						{
							id: 'intro-simple-legend-2',
							kind: 'phrase',
							tagalog: 'Mahaba ang kuwento',
							meaning: 'The story is long',
							audioText: 'Mahaba ang kuwento',
							example: 'A simple description of a story.',
							emoji: 'Long',
						},
						{
							id: 'intro-simple-legend-3',
							kind: 'phrase',
							tagalog: 'Maganda ang alamat',
							meaning: 'The legend is beautiful',
							audioText: 'Maganda ang alamat',
							example: 'A simple opinion about a legend.',
							emoji: 'Beautiful',
						},
					],
					matchPairs: [
						{
							left: 'There is a legend about a mountain',
							right: 'May alamat tungkol sa bundok',
						},
						{ left: 'The story is long', right: 'Mahaba ang kuwento' },
						{ left: 'The legend is beautiful', right: 'Maganda ang alamat' },
					],
					buildPrompt: 'Build "There is a legend about a mountain."',
					buildOptions: ['May', 'alamat', 'tungkol', 'sa', 'bundok', 'bayani'],
					correctSequence: ['May', 'alamat', 'tungkol', 'sa', 'bundok'],
					blankPrompt: 'Complete the legend summary.',
					sentenceTemplate: 'May alamat tungkol sa ___.',
					acceptableAnswers: ['bundok', 'Bundok'],
					placeholder: 'Place',
					listeningPrompt: 'What is the legend about?',
					audioText: 'May alamat tungkol sa bundok',
					listeningOptions: ['a mountain', 'a film', 'a song'],
					correctAnswer: 'a mountain',
					speakingPrompt: 'Say "The legend is beautiful."',
					expectedTranscript: 'Maganda ang alamat.',
					referenceTranslation: 'The legend is beautiful.',
					finalExercise: 'listen-repeat',
				}),
			],
		},
	],
}
